### ISSUE TITLE
Rewrite AT / PS/2 keyboard controller and keyboard and adapt the PS/2 mouse

### ISSUE THREAD

**Issue by OBattler** [86Box/86Box#1089]
Rewrite AT / PS/2 keyboard controller and keyboard and adapt the PS/2 mouse.

**Comment by OBattler** [comment]
This will serve to fix the following issues:
- #1475;
- #1900;
- #1936;
- #2108;
- #2286;
- #2375.

**Comment by OBattler** [comment]
And another one: https://github.com/86Box/86Box/issues/2961 .

**Comment by nephatrine** [comment]
Until this is complete, is there any workaround for games that experience input lockups currently?

**Comment by Korkman** [comment]
Yes, but it comes with a downside: change the mouse from ps/2 to COM port. The downside being the low polling rate of serial mice (choppy cursor). Some games do a pretty good job of compensating for that, which eases the pain a bit.

Cannot guarantee this helps for all situations but I haven't encountered the input dropouts again ever since I changed to serial mouse.

**Comment by OBattler** [comment]
Closing because this is done.
