### ISSUE TITLE
When playing a game, the keyboard does not respond after a period of time.

### ISSUE THREAD

**Issue by shijie001** [86Box/86Box#1101]
When playing a game, the keyboard does not respond after a period of time.

8088 cpu, cga, old dos games
such as digger, round42, pakupaku(pacman)
The configuration of 386, 486 and vga will also have problems

There is a certain degree of randomness, but it will always appear.
Then the game character is out of control and moves all the way to the edge of the screen. It seems that the user is pressing a certain arrow key consistently. The game is still running, but the input fails.
At this time, sending ctrl-alt-del will not work, only hard reset. 

Windows 10
The problem appeared in version 3.0
3.0.0.2654
D:\projects\86Box\86Box-32-9fb3a3ed\
3.0.0.2642
D:\projects\86Box\86Box-32-48883a46\
3.0.0.2625
D:\projects\86Box\86Box-32-cfb559de\
3.0.0.2613
D:\projects\86Box\86Box-32-5e470656\

I have tested these 2.x versions many times and there is no problem.
2.10.0.2374
D:\projects\86Box\86Box-32-5290bcf7 
2.10.0.2018
D:\projects\86Box\86Box-32-15bf5841\
2.7.0.2008
D:\projects\86Box\86Box-32-245af88d\

**Comment by shijie001** [comment]
![freeze](https://user-images.githubusercontent.com/25165513/99610348-9d4ecb80-2a4c-11eb-9873-2fbd3c8bf6d6.png)
Suddenly the key is not responding, and the game is still running.

**Comment by maximus105** [comment]
@shijie001 In which build did this bug appear, and which one else did it not?

**Comment by shijie001** [comment]
> @shijie001 Which build did this bug appear in, and which hasn't had this bug yet?

The problem appeared in 
3.0.0.2654
D:\projects\86Box\86Box-32-9fb3a3ed
3.0.0.2642
D:\projects\86Box\86Box-32-48883a46
3.0.0.2625
D:\projects\86Box\86Box-32-cfb559de
3.0.0.2613
D:\projects\86Box\86Box-32-5e470656\

there is no problem in 2.x 
2.10.0.2374
D:\projects\86Box\86Box-32-5290bcf7
2.10.0.2018
D:\projects\86Box\86Box-32-15bf5841
2.7.0.2008
D:\projects\86Box\86Box-32-245af88d\

**Comment by maximus105** [comment]
@shijie001 I meant to check only two builds to pinpoint this bug. For example, in build 2600 this bug appeared, but in build 2559 this bug was not yet present. Can you check it this way?

**Comment by shijie001** [comment]
> @shijie001 I meant to check only two builds to pinpoint this bug. For example, in build 2600 this bug appeared, but in build 2559 this bug was not yet present. Can you check it this way?

3.0.0.2625 (bug)
86Box-32-cfb559de

2.7.0.2008 (no bug)
86Box-32-245af88d

**Comment by maximus105** [comment]
Well, this is too big a discrepancy between builds 2625 and 2008. Could you more accurately determine the build where this bug appeared? For example, there is a bug in build 2625. And in build 2624? The point is to accurately determine the build that does not have this bug and the next build, after which there is already this bug (What would be the difference between the builds 1. For example, build 2625 and build 2624)

**Comment by maximus105** [comment]
A bug with a broken keyboard is most clearly seen in GOODY and THE LAST MISSION games. I've checked several builds. In build 2579 on 8088 and 8086 machines, the keyboard works fine in these games. And in build 2580 in these games the keyboard does not work on all 8088 machines and on some 8086 machines (Amstrad PC1512, Amstrad PC1640, Compaq Deskpro, Olivetti M24). This bug appeared in build 2580 and persists until the last build.

![20201123-180009-550](https://user-images.githubusercontent.com/58270614/99999539-f90cb200-2dc8-11eb-8a5a-a94f9507974d.png)

![20201123-180028-622](https://user-images.githubusercontent.com/58270614/99999563-02961a00-2dc9-11eb-944a-3ee8f5e3db91.png)

Also, this bug randomly appeared in the game DIGGER, when during the game the keyboard stopped responding to pressing the arrow keys (up, down, left, right).

![20201119-144810-362](https://user-images.githubusercontent.com/58270614/99999510-edb98680-2dc8-11eb-8cee-b5065631e14c.png)

**Comment by maximus105** [comment]
Anyway, I'm staying on build 2579. Nothing has been broken in games it in the [8088] and [8086] machines yet.

**Comment by OBattler** [comment]
Can you upload the entire VM so I can reproduce the bug?

**Comment by maximus105** [comment]
Here is the 8088 VM with these games. The control keys in these games are visible in the screenshots above in this thread.
[86Box.zip](https://github.com/86Box/86Box/files/5648610/86Box.zip)

**Comment by maximus105** [comment]
In these games, the keyboard does not work right away. Or you can accidentally enter the game itself on the first level, but then the keyboard definitely does not work. It is not known if this bug is related to the above bug, that in some games (DIGGER) the keyboard stops working after a while. But, at least in these games (GOODY, LIVING, THE LAST MISSION) the keyboard doesn't work right away. In the configured VM that I added above, you can run these games and see this bug.

**Comment by maximus105** [comment]
A bug with the keyboard (the keyboard stopped responding, as if the left arrow key was stuck) appears a minute later in the DIGGER game on the machine [8088] Zenith Data Systems SuperPort (Z-184).

![2020-12-23_134932](https://user-images.githubusercontent.com/58270614/102993807-85c0a200-4526-11eb-9dc7-90191d3e2d93.png)

**Comment by maximus105** [comment]
Currently in the latest build 2771, when new XT machines have already been added (eg [8088] Zenith Data Systems SuperPort (Z-184), the keyboard seems to work properly in GOODY, LIVING, THE LAST MISSION games only in these newly added XT machines and some new ones added later, but does not work in all other XT machines that were added a long time ago. But in the DIGGER game in the latest builds, the keyboard also stops responding after a while (like a sticky key) in these new XTs machines and also old ones. And in build 2579 everything works fine in all XT machines. Is it possible to determine which fix caused this bug after build 2579 and fix this bug in all XT machines where it manifests itself?

**Comment by maximus105** [comment]
This bug with a broken keyboard occurs in XT machines that were added a long time ago, but after build 2579. In the latest build 2803, in some XT machines that were added relatively recently, in LIVING, GOODY, THE LAST MISSION games, the keyboard may work correctly, but in In DIGGER, the keyboard does not work (stops responding or the key sticks) on all XT machines 8088 and 8086. Did you reproduce this bug with the keyboard?

**Comment by maximus105** [comment]
Also, a bug with a stuck keyboard key appeared when playing Duke Nukem 3D for 5 minutes on the [i440BX] ASUS P3B-F machine.

**Comment by qeeg** [comment]
> Also, a bug with a stuck keyboard key appeared when playing Duke Nukem 3D for 5 minutes on the [i440BX] ASUS P3B-F machine.

This bug is likely separate from the other bugs, given that XT-class keyboards and AT and PS/2-class keyboards are completely different.

**Comment by OBattler** [comment]
Not necessarily, as nothing prevents Duke Nukem 3D to rely on the same reserved PIC read as those 808x games, and therefore running into the same problem.

**Comment by maximus105** [comment]
The issue was not fully fixed. In the game SHAMUS (1984), after about 1 minute of playing, the keyboard freezes and stops responding to pressing. Perhaps these keyboard freezes also appear in the game DIGGER, PRINCE OF PERSIA and DUKE NUKEM 3D, but the game SHAMUS allows you to determine this most accurately. I determined exactly in which build this bug appeared. Build 2579 did not have this bug in SHAMUS, but build 2580 already has it. I added a virtual machine with SHAMUS to reproduce this bug.
[86Box.zip](https://github.com/86Box/86Box/files/6230774/86Box.zip)

**Comment by OBattler** [comment]
It's not the keyboard that freezes, but the entire game since the non-player enemies stop moving as well.

**Comment by maximus105** [comment]
I tested SHAMUS, DIGGER, PRINCE OF PERSIA, DUKE NUKEM 3D and several other games in build 2875. Played these games for 5-10 minutes. Everything works fine, there are no game freezes or keyboard freezes.

**Comment by maximus105** [comment]
A keyboard bug has been found in BUCK ROGERS. If you press and hold the control key (arrow or SPACE or any other key) in the game itself, the game will freeze with the error message "Internal stack overflow. System halted" (as in the screenshot):

![2021-04-04_104409](https://user-images.githubusercontent.com/58270614/113506843-c8dfd780-954f-11eb-9ba0-eade3e2ae60a.png)

This bug is only present on the [8088] American XT computer since build 2558, where this machine was first added, and may appear on some 286, 386 machines. Most 8088, 8086 machines do not have this bug. Also there is no this bug in DOSBox-X. I added a virtual machine with the game BUCK ROGERS to reproduce this bug.
[86Box.zip](https://github.com/86Box/86Box/files/6254421/86Box.zip)

**Comment by OBattler** [comment]
Are you sure this does not occur on the real American XT Computer?

**Comment by maximus105** [comment]
A keyboard bug has been found in Dyna Blaster. In the game menu and in the game itself, the control keys (arrows) do not work, only the control keys on the numeric keypad do. In addition, if you press the control keys on the numeric keypad in the game itself, then the controlled character of the game will stick (as if a key is stuck), move with a delay, or even move in the other direction. System requirements for this game: 286 processor or higher. I remember exactly that on a real PC i386DX-40 the keyboard in this game worked fine without bugs and sticking. This bug in 86Box is present only on machines 286, i386SX, i386DX, i486. Starting with Socket 4 and higher, this game does not have this keyboard bug. Also there is no this bug in DOSBox-X.
1. For i386DX, i486 this bug appeared in build 2516 and is valid until the last build (in build 2515 everything works fine for i386DX, i486).
2. For 286, i386SX, I have not yet been able to identify the assembly in which this bug appeared. I ran build 2200 and it already has this bug for 286, i386SX. Perhaps even earlier builds need to be checked. I added a Dyna Blaster virtual machine to reproduce this bug.
[86Box.zip](https://github.com/86Box/86Box/files/6273903/86Box.zip)

**Comment by maximus105** [comment]
I was able to figure out the following:
1. For 286, i386SX this bug appeared in build 2032 and is valid until the last build (in build 2030 everything works fine for 286, i386SX).
2. This game also works in 86Box on 8088 and 8086 processors. This keyboard bug is not present in early builds, for example build 2030. The latest build 2898 on 8088 and 8086 processors also does not have this bug in this game.

**Comment by maximus105** [comment]
A keyboard bug that was found in the game BUCK ROGERS on [8088] American XT computer shows up in pure MS-DOS v3.30 and v6.22. If you press and hold a control key (arrow, spacebar, or any other key) in pure DOS (for example, at boot time), the [8088] American XT computer will freeze with the error message “Internal stack overflow. System halted" (as in the screenshot):

![2021-04-25_174659](https://user-images.githubusercontent.com/58270614/115998576-8a8a8500-a5f0-11eb-95b6-2545bf454b43.png)

Perhaps this bug has something to do with keyboard repeat emulation (the repeat sound sounds different from other 8088 HT machines). This bug is only present on the [8088] American XT computer since build 2558, where this machine was first added, and may appear on some 286, 386 machines. Most 8088, 8086 machines do not have this bug in 86Box.
