### ISSUE TITLE
Stratego graphics issues 

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#1436]
**Describe the bug**

1.There is a graphics bug in the EGA video mode of the game:
2. The native Hercules graphics video mode does not work with thids game.

**Note:** The game supports VGA,EGA, TANDY 1000, CGA and Hercules natively (no CGA emulation needed!)

Here is the game floppy disk:

[Stratego.zip](https://github.com/86Box/86Box/files/6449965/Stratego.zip)

**To Reproduce**

1. Start the a virtual machine with a XT or 286 and EGA or Hercules graphics card.
2. At DOS prompt type"stratego" and the press enter.
3. The colors are wrong in the EGA video mode. On the Hercules video mode, there is only black screen after the Rawcopy crack notice.

**Expected behavior**
The EGA and Hercules video modes works just fine under regular DosBox 0.74.

**Screenshots**
86Box screenshots:

![86box 001](https://user-images.githubusercontent.com/31600563/117615387-0c75c480-b140-11eb-9aa7-d2c913441e28.png)
![86box 002](https://user-images.githubusercontent.com/31600563/117615394-0ed81e80-b140-11eb-9380-a341a7e03b4f.png)

![86box 003](https://user-images.githubusercontent.com/31600563/117615380-097ad400-b140-11eb-9c3f-8123d94aaef8.png)

DosBox 0.74 Screenshots using EGA video mode on DosBox: (No VGA)

![DOSBOX EGA001](https://user-images.githubusercontent.com/31600563/117615454-244d4880-b140-11eb-99e6-0189ccc13ac6.png)
![DOSBOX EGA002](https://user-images.githubusercontent.com/31600563/117615457-24e5df00-b140-11eb-9104-754e04d97606.png)
![DOSBOX EGA003](https://user-images.githubusercontent.com/31600563/117615465-26170c00-b140-11eb-9bf0-c8f344896887.png)

Dosbox 0.74 Hercules video mode:

![DosBox 0 74 Hercules 001](https://user-images.githubusercontent.com/31600563/117615877-bc4b3200-b140-11eb-841b-ba3854f28606.png)
![DosBox 0 74 Hercules 002](https://user-images.githubusercontent.com/31600563/117615881-bce3c880-b140-11eb-9171-f772578e3cd0.png)
![DosBox 0 74 Hercules 003](https://user-images.githubusercontent.com/31600563/117615882-bd7c5f00-b140-11eb-8bf2-fb1ba82bff33.png)
![DosBox 0 74 Hercules 004](https://user-images.githubusercontent.com/31600563/117615883-bd7c5f00-b140-11eb-8536-0f7a33cb1479.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 2004
 - 86Box version: 3.0.0.2986
 - Build type: Dev

**Additional context**
The game works fine with Tandy 1000 SL.

**Comment by OBattler** [comment]
Are you sure you're not trying to run the EGA driver on a VGA?

**Comment by Fenix770** [comment]
This game has autodetection of the video card: It can be VGA, EGA, Tandy, CGA or Hercules. It detects the EGA video card correctly on DosBox. I'd not know if the video mode can be overridden, like the game Pictionary, which has autodetection and parameters to force EGA, CGA, Tandy or Hercules.

**Comment by OBattler** [comment]
OK, it's actually using the VGA driver on an EGA, as indicated by the fact the bottom of the picture is missing. So it's basically thinks the EGA is the VGA.

**Comment by iamgreaser** [comment]
I slapped together a log showing the part that is most likely doing the detection.

```
      1 EGA OUT 03C0 20
        ...
  60571 EGA IN  03DA
      1 EGA OUT 03C0 0F
      1 EGA OUT 03C1 3F
      1 EGA OUT 03C0 32
      1 EGA OUT 03C1 0F
      3 EGA IN  03DA
      1 EGA OUT 03C0 32
      1 EGA OUT 03C1 0F
      2 EGA IN  03DA
      1 EGA OUT 03C0 32
      1 EGA OUT 03C1 1F
      2 EGA IN  03DA
      1 EGA OUT 03C0 32
      1 EGA OUT 03C1 2F
      2 EGA IN  03DA
```

You can twiddle with bits 4 and 5 of the status register but if you somehow freeze them into place then this will read 65537 times and then be done with that particular output.

It seems like the Compaq EGA, which has to emulate those bits better than the IBM EGA does in order to get the video BIOS to boot, can get a bit further past that. But then there seems to be another test which follows which I haven't deciphered yet.

**Comment by dbalsom** [comment]
I have a theory about what's going on, at least for the EGA issue. It works in Hercules mode for me.

I don't think the game's EGA detection is very good, or if it's really "detecting" EGA at all. I can't find really any relevant detection code at all - that doesn't mean it's not there and I'm just not missing it somehow, but it doesn't read a lot of video registers which really limits the number of ways by which it could try to detect an EGA card on its own.  I think the way its "detection" works is that it tries to set a VGA graphics mode via int 10h first, and then checks to see if that fails.

On a real IBM 5150 it fails to initialize a Tandy EGA card (fairly early clone 256k model with 5 LSI chips) - the card goes into 40 column text mode and stays there while the theme music plays. This is Not A Good Sign.

It works on an AST EGA Plus II card (a much later, 1-chip EGA clone)

It fails to initialize on MartyPC's IBM EGA emulation
It fails to initialize on 86Box's IBM EGA emulation
...But it works on 86Box's EGA Wonder 800+ emulation. 

As for DosBox. DosBox's video log shows:

   9512460       INT10:Set Video Mode 12
   9512460 ERROR INT10:EGA:Trying to set illegal mode 12
   9512526       INT10:Set Video Mode 13
   9512526 ERROR INT10:EGA:Trying to set illegal mode 13
   9512594       INT10:Set Video Mode D

So Stratego tries to set DosBox into VGA mode 12h and DosBox, knowing it set to machine=EGA just says nope and so the game falls back to EGA.  I'm speculating here after a bleary few hours of staring at this in Ghidra last evening, but I think this behavior would be BIOS-dependent.  The behavior of the IBM EGA BIOS when mode 12h is set is to sort of shrug and use the CRTC parameters from mode 10h rather than overflow the parameter table, but the mode byte of 12h gets set in the bios data area anyway, so Stratego thinks we've had Great Success. This is how we have correct parameters for 640x350 mode; which by happy accident is compatible enough with the VGA's 640x480 mode that we just see a stretched picture and bad colors.

This is going to be reliant on certain specific BIOS behavior. EGA cards produced after the VGA standard came out, or at least cards that handle unsupported modes differently, might treat mode 12h more cautiously and not pass it through to the BDA, letting Stratego realize it failed to set the VGA mode, where it can then fall back to EGA properly.

There is some good news, though. You can simply run

stratego ega

to override this 'detection' logic.

**Comment by dbalsom** [comment]
Sort of confirming my theory, here is what Statego looks like (without the 'ega' parameter) on a IBM 5170 with an original IBM EGA card:

![image](https://github.com/86Box/86Box/assets/7229541/19d68de9-9a5b-4d33-9be9-66254fcce962)
