### ISSUE TITLE
3dfx Voodoo 1 + Dos6.22 + Screamer Rally

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#1575]
### Discussed in https://github.com/86Box/86Box/discussions/1574

<div type='discussions-op-text'>

<sup>Originally posted by **Zilog80c** August  2, 2021</sup>
Hi to all, 
 i have a problem with 3dfx Voodoo 1 with Screamer Rally. 
The conf is Asus P6UPS Pentium 133 / S3 Vision 868, 3DFX Voodoo Graphics 1, Vram 2+2 Mb. Dos v6.22
When Run the Games i have or error or glich
![SC2](https://user-images.githubusercontent.com/31391699/127910121-fd6c1e22-a980-4d1a-9d55-4686c415eac3.JPG)
![SC2_glich](https://user-images.githubusercontent.com/31391699/127910102-cc3760c3-7891-4f58-ad68-82e3306d9f83.JPG)

 Thanks a lot for Help.
 </div>

**Comment by OBattler** [comment]
Can you provide evidence that this does not occur on real hardware?

**Comment by AITUS95** [comment]
i don't know if it helps but i played the game on dosbox-x with voodoo emulation without glitch

![screen](https://user-images.githubusercontent.com/48457684/131233577-d1bd1855-ce6a-4bd5-9750-c02caa95ae9a.PNG)

**Comment by OBattler** [comment]
This looks like the 64-bit Voodoo recompiler bug.

**Comment by Kappa971** [comment]
I have a similar problem:
![scr1](https://github.com/86Box/86Box/assets/62349018/7dc9a630-45e9-4ba5-a4e0-7d7284eefd21)

Emulated machine: Pentium MMX 233MHz, 64 mb RAM, Voodoo 1, Windows 95C.
I have the same problem with all tested 86box versions (Old Recompiler, New Recompiler, 32bit, 64bit, v3.11, latest build). The game seems to have no graphical issues with a Voodoo 2 but crashes after a few seconds. Screamer Rally came out in 1997, so it probably only supports Voodoo 1.

**Comment by Kappa971** [comment]
I found a working Voodoo 2 driver for Screamer Rally [voodoo2-210.zip](https://github.com/86Box/86Box/files/12431545/voodoo2-210.zip) (just copy glide2.ovl to game folder and set 2mb limit in Voodoo 2 control panel), performance is not that great (probably due to pentium MMX. The emulation is running at 100%) but no graphical glitches, so I guess there is something wrong with the Voodoo 1 emulation.
From what I could see, all the pre-1998 Glide games are all games designed for Voodoo 1, including Screamer Rally which installs its glide2x.ovl driver for Voodoo 1 into the game folder. If it doesn't detect a Voodoo 1, it doesn't install the 3DFX driver (so I don't understand on the web why they write that the game supports Voodoo 2 when instead the game came out a year before Voodoo 2).
I'm not a programmer but I'm available for any test.

**Comment by OBattler** [comment]
Closing this as this is basically being tracked in #2923.

**Comment by Kappa971** [comment]
This issue is not listed here https://github.com/86Box/86Box/issues/4483.
I haven't used 86Box in a while, has this bug been fixed?

**Comment by OBattler** [comment]
Listed it there now.

**Comment by OBattler** [comment]
This is now fixed.
