### ISSUE TITLE
Please add Russian Language to Interface

### ISSUE THREAD

**Issue by Danik2343** [86Box/86Box#1877]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
Add Russian language support for the interface.

**Describe alternatives you've considered**
English Language

**Additional context**
You can enable the voluntary translation function for all users, through special services, into languages such as Chinese (Included in 86Box) and e.t.c

**Comment by maximus105** [comment]
Grammar errors were found in Russian translation for 86Box. Where can I download the translation file to fix these errors? I could fix these errors.

**Comment by Cacodemon345** [comment]
@maximus105 https://github.com/86Box/86Box/blob/master/src/win/languages/ru-RU.rc

**Comment by KeishiX** [comment]
I've also done some changes to this translation. Is it ok if I create a pull request?

**Comment by maximus105** [comment]
Perhaps these grammatical errors have already been corrected. I'll double-check and report back if I find any grammatical errors.

**Comment by maximus105** [comment]
Found grammatical errors:
On line 472, the word "жесткую" should contain the letter "ё" instead of the letter "е".
On line 482, the word "жесткой" should contain the letter "ё" instead of the letter "е".
On line 537, the word "жесткий" should contain the letter "ё" instead of the letter "е".
On line 547, the word "жесткого" should contain the letter "ё" instead of the letter "e".
On line 568, the word "Дифференцированнный" should be so "Дифференцированный" ("нн" instead of "ннн").
On line 573, the word "дифференцированнный" should be so "дифференцированный" ("нн" instead of "ннн").
