### ISSUE TITLE
Using ISA RTC module causes 86box to crash and lose CMOS settings

### ISSUE THREAD

**Issue by Dungeonseeker** [86Box/86Box#1928]
**Describe the bug**
When using any of the ISA RTC cards 86box will crash everytime you change any hardware at the point where you click OK to a hard reset, after the crash the system comes back up with CMOS defaults loader. I noticed it only ever seems to create a 1kb file in the nvr folder

**To Reproduce**
1. Create any ISA system
2. Add an ISA RTC Card
3. Start 86box
4. Go into BIOS, set options and save
5. Go back to 86box settings and change the amount of RAM
6. Hit Apply then click OK to a hard reset
7. 86box crashes out and on next launch all saved settings are lost

**Expected behavior**
That adding or removing RAM from a VM won't cause it to lose all CMOS settings

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win 11 Pro
 - 86Box version: 3.0.0.3333
 - Build information: X86_64

**Additional context**
None

**Comment by OBattler** [comment]
Why would you even need an ISA RTC card on a machine with CMOS setup, which by definition is going to have an on-board RTC already? All that does is creates a conflict, which is why you get a crash.

Of course, the best idea would be to add a MACHINE_RTC flag that tells the Settings dialog the machine has a RTC already, and therefore disable the ISA RTC setting. But that's a separate thing.

Therefore, I'm closing this for not being a bug.

**Comment by dhrdlicka** [comment]
I would say 86Box outright _crashing_ is very much a bug.
