### ISSUE TITLE
NEXTSTEP doesn't install if you don't compile with presets

### ISSUE THREAD

**Issue by mariuszkurek** [86Box/86Box#2171]
**Describe the bug**
I've got this comment under 86box AUR package:

The code produced by the PKGBUILD doesn't work correctly because of missing compiler flags (-fno-strict-aliasing, and for Intel additionaly -mstackrealign). Try, for example, installing NEXTSTEP in an emulated Pentium machine. It behaves extremely erratic and is impossible to install. Instead of adding these flags, I've changed the PKGBUILD to use the provided cmake configuration files and disable the makepkg provided build flags. This leads to the usage of the correct compiler flags and NEXTSTEP works nicely.

`PKGBUILD` is a script to compile a package, invoked using `makepkg` command; power users usually put `-march=native` or similar in these flags, making it effectively Optimized.

**To Reproduce**
1. Compile without the use of Ninja or providing CFLAGS.
2. Make a Pentium machine (author didn't specify which one, but it sounds like it's a CPU issue).
3. Try to install NEXTSTEP.

**Expected behavior**
NEXTSTEP installs without any problems.

**Desktop:**
 - OS: Arch Linux
 - 86Box version: 3.2.1
 - Build information: x64, `cmake -DRELEASE=on -DUSE_QT6=on -DSLIRP_EXTERNAL=on -DNEW_DYNAREC=off`

**Comment by OBattler** [comment]
There were 64-bit old recompiler bugs due to the fact I made it emit some code that only worked in specific circumstances. It was causing all sorts of issues when running 64-bit 86Box, even when compiled with the presets. On the reporter's specific platform, the presets likely just masked those problems by linking the code such that the inappropriate behavior of my emtited code was never triggered. This is now fixed. So I'm closing this, but it can bre reopened if my assessment is found to be wrong.
