### ISSUE TITLE
Crashes with Olivetti M24 emulation

### ISSUE THREAD

**Issue by jvernet** [86Box/86Box#2244]
**Describe the bug**
I'm experiencing random but frequent crashs with the Olivetti M24/AT&T 6300 emulation, mostly when trying to use AT&T video mode. 86Box simply quit.

**To Reproduce**
1. Use the machine config below
2. Start and go to C:\TC
3. Launch BGIDEMO.EXE
4. 86Box will quit without any warning, sometime right at start, sometime at the end. Try to use Turbo C, you can start. It uses to work a while back (more than 1 year ago)

More over, the Olivetti Diag (CUSTORMER.EXE) reports bad motherboard switch form RAM SIZE.

**Expected behavior**
No crashes !
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64Bits (see log)
 - 86Box version: 3702

[Oliveti 1600.zip](https://github.com/86Box/86Box/files/8317938/Oliveti.1600.zip)

**Comment by EngiNerd89** [comment]
Hello, I made some tests and found out that this issue is not specific to the Olivetti M24 or the OGC adapter, but it affects all CGA and super-CGA (like OGC, Compaq and NGA) adapters if overscan is active. Disabling overscan no longer causes random segfaults when switching display mode, so it appears to be somewhat related to the usage of negative values when passing display lines in video_blit_memtoscreen

Unfortunately, I've been unable to investigate the problem further. I hope this input may be still useful though.

**Comment by OBattler** [comment]
This has since been fixed.
