### ISSUE TITLE
Mouse cursor not captured correctly when accessing Linux through VNC

### ISSUE THREAD

**Issue by atylmo** [86Box/86Box#2331]
**Describe the bug**
Okay, this is a pretty niche thing but the mouse cursor doesn’t get captured or move around the VM window when I’m connected to the host desktop with VNC.

**To Reproduce**
1. Make a Windows (98) VM with 86Box on Linux
2. Connect to the Linux host with VNC
3. Through VNC, click in the VM window to capture the mouse
4. Try to move the mouse around
5. Notice that the mouse cursor is invisible and does not appear to do anything except make the active window inactive. Sometimes it stays locked in the window, but sometimes it allows me around the rest of the host desktop.

**Expected behavior**
The mouse cursor should track with the VNC cursor and allow me to click within the VM.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - 86Box version: 3.4.1
 - Build information: x64 old dynarec AppImage

**Additional context**
I’ve tried two VNC clients (Jump Desktop and Apple’s Screen Sharing) and they both have the issue.

I’m honestly not sure where to file this. It could be a VNC bug but the mouse works correctly in GNOME Boxes.

**Comment by OBattler** [comment]
It appears to be a Wayland to X translation bug - I have equally bad behavior in a Hyper-V Linux VM - when I capture mouse, the cursor correctly disappears, but with it, so do all the mouse events, because it appeats the Wayland to X translation tracks the position of the cursor and if the cursor is in any way made invisible, it basically ignores the mouse. There is no way around it, I tried multiple methods to make the cursor invisible, all with the exact same results.

**Comment by OBattler** [comment]
Closing due to it being tracked in the common issue #4239.

**Comment by OBattler** [comment]
Invisible cursor on capture is fine. The cursor not doing anything when invisible is, however, a Wayland bug. I've encountered it when running 86Box on Linux under VMWare. It can't be fixed since none of the methods I tried, worked. So unfortunately, CANTFIX.
