### ISSUE TITLE
CGA - Windows - Blink

### ISSUE THREAD

**Issue by Alejo808** [86Box/86Box#2354]
**Describe the bug**
the integrated graphics card of the livetti Mxx generate a constant flicker in the first 4 or 5 lines of characters. this does not occur in the 3614 or earlier compilation, nor in the Linux Bild.
PS- it also happens with the generic CGA board, but in this case only in the first line of pixels flickers

**To Reproduce**
default configuration of ls olivetti Mxx or any other PC with CGA board. in windows build

**Screenshots**

![Captura de pantalla 2022-05-20 090958](https://user-images.githubusercontent.com/102820458/169526845-3e630cfc-924f-4896-9670-c1f30ff8ce52.png)

![Captura de pantalla 2022-05-20 090903](https://user-images.githubusercontent.com/102820458/169526903-17b907ae-ce76-40d5-9876-2c672fe66cfe.png)

alternates between these two states intermittently

**Desktop (please complete the following information):**
 - OS: Windows 10 64Bits 
 - 86Box version: 3.4.1 Build 3738 32/64Bits (upgraded to 3.5 Build 3777 -same error )

**Comment by Alejo808** [comment]
--- the configuration file, completely by default. I just created it to check that the effect persists

------------------------------------------------------------------------------------------------------
[General]

vid_renderer = qt_software

[Machine]
machine = m24
cpu_family = 8086
cpu_speed = 7159092
cpu_multi = 1
cpu_use_dynarec = 0
time_sync = disabled
mem_size = 128

[Video]
gfxcard = internal

[Input devices]
mouse_type = none

[Storage controllers]
hdc = none
cassette_enabled = 0
cassette_mode = load

[Olivetti M21/M24/M28 (GO317/318/380/709) video card]
rgb_type = 2
snow_enabled = 1

------------------------------------------------------------------------------------------------------

**Comment by OBattler** [comment]
> alternates between these two states intermittently

What you describe there, is the cursor blinking. That's normal and happens on real hardware as well.

Now, with the config you posted, I get an entire line blinking, but it's because the BIOS repeatedly does this:
- Attempts to boot from floppy;
- Fails because there is no floppy inserted;
- Goes back to the beginning of the line and clears the line;
- Then goes back to the beginning of the line again and outputs the error message.

As such, that's not something I can change in any way.

As such, this is being closed with NOTABUG.

**Comment by OBattler** [comment]
Wait a second...

> PS- it also happens with the generic CGA board, but in this case only in the first line of pixels flickers

We did have this top flicker, I rememebr it, but it has since been fixed.

**Comment by Alejo808** [comment]
https://user-images.githubusercontent.com/102820458/187082554-86a7ef93-d9b2-45dd-9c75-82742fdedae2.mp4


https://user-images.githubusercontent.com/102820458/187082559-c0c0cb9c-4528-4405-9131-f307c2f52dc1.mp4

made with the latest stable compilation.....

**Comment by OBattler** [comment]
I see no bug on CGA, but I do see the top lines disappearing on the Olivetti.

**Comment by Fenix770** [comment]
Hello!

Maybe is not related, but the Sigma Color 400, works only on MR BIOS (tested MR 286) and detects it as EGA/VGA instead of CGA. Other machines either crash at startup or write lines that disappear (I think it misdetects it as EGA on these machines too)
I don't know if apply to other CGA cards that suppors extra video modes (the Olivetti support 640x400x2)
The Sigma is based on the CGA card with the extra video modes (640x400 at 2,4,8 or 16 colors)
