### ISSUE TITLE
AppImage does not show icon from .desktop shortcut

### ISSUE THREAD

**Issue by dunestorm333** [86Box/86Box#2358]
The AppImage from the file browser (in this case Nautilus) displays a shortcut as normal.
![image](https://user-images.githubusercontent.com/13191298/169713568-9aa43bb3-08a5-47ef-9b1f-c809a0f8fe2e.png)

However when using AppImageLauncher which automatically creates .desktop files, the icon never shows for 86Box. This has been tested both on GNOME 42 and KDE Plasma 5.24. Other apps have no issues presenting icons to system menus.

![image](https://user-images.githubusercontent.com/13191298/169713550-0be2b1d1-25ec-479e-a975-dc191272c551.png)

**Comment by richardg867** [comment]
Fixed by e7a078b, although I wouldn't really advise opening 86Box from an app launcher until the built-in manager is ready, since the emulated machine files will be stored wherever the launcher's current directory is; my Ubuntu test machine uses the home, but it can be anything else, including non-writable places such as `/`.
