### ISSUE TITLE
Increased CPU usage of the Qt build

### ISSUE THREAD

**Issue by dhrdlicka** [86Box/86Box#2391]
### Discussed in https://github.com/86Box/86Box/discussions/2390

<div type='discussions-op-text'>

<sup>Originally posted by **ArnoldUK** June 15, 2022</sup>
I've been using old version 2.07 for quite a while and since upgrading to version 3.0 the renderers are all opengl and vulkan. using any opengl renderer causes very high CPU usage even for basic 8mhz machine. The directx renderers did not cause high cpu usage and were much more cleaner video display. Just wondered why the switch from directx to opengl ?</div>

**Comment by OBattler** [comment]
This has turned out to have nothing to do with QT. Also, it might have been caused by an unknown cause (PIT rewrite?) and then later further exacerbated by the switch to XAudio2/FAudio. The only way to find out the true case is for one of the affected people to bisect and identify the exact build that increased the CPU usage.
