### ISSUE TITLE
[Feature] Toggle-able drag and drop storage insertion

### ISSUE THREAD

**Issue by piegit** [86Box/86Box#2405]
**Is your feature request related to a problem? Please describe.**
If a OS install requires you to have a lot of floppies it gets really tiresome having to press eject and finding the next floppy in line.

**Describe the solution you'd like**
I want there to be a button in the tools menu that can toggle drag and drop on and off.

**Describe alternatives you've considered**
Excluding the hard drive, double click on the attached storage at the bottom of the screen to eject it.

**Comment by dhrdlicka** [comment]
You don't have to press eject though. Just mount the next image in line without ejecting.

**Comment by ArnoldUK** [comment]
I can live with the extra button click to eject a floppy, that's how it was done with a really floppy drive anyway.
Adding drag and drop is just as long as pressing a button. You can insert a new floppy disk without having to eject it anyway. I would not like to see any kind of drag and drop feature implemented but maybe a clipboard shared between host and guest.

**Comment by OBattler** [comment]
As I said, drag and drop has already been added, though it's not mandatory to use, the old methods to mount floppy images are still available.

Also, a clipboard shared between host and guest would be very difficult to add, one reason being possible character set differences.

In any case, I'm closing this since the original request has been fulfilled.
