### ISSUE TITLE
Redo ISA/VLB/MCA/PCI card configuration

### ISSUE THREAD

**Issue by MoochMcGee** [86Box/86Box#259]
Basically, we need to be able to have a certain number of slots, and any card can go into any slot. Yes, this means we'll have to support MDA and CGA both in the same system and connected to different monitors. This will also help things like combo cards like the NV1 be able to have both audio and video on the same PCI function.

**Comment by OBattler** [comment]
For PCI, this is basically already done as PCI relies on ther being a fixed number of slots the motherboard BIOS knows about, otherwise you get PCI devices with unassigned IRQ's, etc.
For MCA this is also basically already done, the slots are limited.
For ISA and VLB - I know that ISA riser cards that add extra slots exist, so there's no real limit to ISA slots, but I have no idea as for VLB.
The dual graphics card thing is an entirely separate issue and could be done by separating the render window from the main window, allow each graphics card to create a new render window on in it, and having the blit memtoscreen functions specify the ID of the virtual screen to blit to.
I'm closing this for time being to reduce clutter on the issues page but I'll definitely be going back to this one in the future.
