### ISSUE TITLE
Ability to enable SLI on regular Voodoo1

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#2592]
**Describe the bug**
On a real PC, a regular Voodoo1 does not support SLI. Why is it possible to enable SLI in 86Box for it? When SLI is enabled in the 86Box on a regular Voodoo1, you cannot set the resolution to 1024x768 in Quake1 for DOS(3Dfx) and Quake2 for DOS(3Dfx). That is, SLI is not supported and does not work in a regular Voodoo1. While in Voodoo2 SLI you can set the resolution to 1024x768 in Quake1 for DOS(3Dfx) and Quake2 for DOS(3Dfx). So it makes sense to remove the ability to enable SLI in 86Box on a regular Voodoo1 video card.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v21H2
 - 86Box v3.7.1 x64 Build 4035
Build type: regular, old recompiler.

**Comment by OBattler** [comment]
Because right now, we can't selectively enable/disable device configuration options based on another option. And given that two out of three card types are known for being able to officially do SLI, I'm not going to go out of my way to code that just because of the remaining third.

**Comment by lemondrops** [comment]
IMO, an ideal solution would entail splitting the `voodoo_device` `device_t` into three separate devices for Voodoo 1, Obsidian SB50 and Voodoo 2, each with their own `device_config_t`'s with appropriate options, limits and defaults for each card; then they would be selectable from a combobox directly on the Video tab instead of the device config. However, configuration option migration could present a problem.

**Comment by OBattler** [comment]
Actually, it appears the Voodoo 1 *chip* does support SLI and there were later cards that could do Voodoo 1 SLI with two chips on the same card: https://www.voodooalert.de/board/forum/index.php?thread/24336-stoned-shaman-20mb-voodoo-graphics-sli-review . So it's actually a legitimate settings.
