### ISSUE TITLE
Typing a HDD size like "1000"MB switches to Custom (Large) but then reverts to "999"MB

### ISSUE THREAD

**Issue by Xuser641** [86Box/86Box#2601]
**Describe the bug**
Typing a HDD size like "1000"MB switches to Custom (Large) but then reverts to "999"MB. this also happens typing in a size like "2000"MB which is changed to "1999"MB, even if you type the number somewhere else (e.g. notepad) and copy it in it still changes.

**To Reproduce**
1. Go to Tools-Settings-Hard Disks
2. Click on New...
3. Try to type in a HDD size in MB like "1000" or "2000"
4. See it change to "Original number -1" (e.g. "1000" changed to "999")

**Expected behavior**
It should stay at the number you type in.

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - 86Box version: 3.7.1 Build 4032
 - 64 bit version

**Comment by kurumushi** [comment]
This actually happens with any disk that uses the "Custom (large)..." type. The same thing happens for example if you type 505 into the size field.  You you can actually manually add a 1 to the cylinders after this happens and get the requested size, so I'm assuming the problem is happening when the cylinders are being recalculated to match the size.
