### ISSUE TITLE
What can I use to determine the maximum cpu my system will emulate reliably?

### ISSUE THREAD

**Issue by dfgdgdgfd** [86Box/86Box#264]
My general guide has been if there's sound distortion at the command prompt, it's not fast enough, but without this (even if the emulation % speed is slightly over or under 100) then it works fine.  But is there anything I can use To benchmark and be certain?

**Comment by dhrdlicka** [comment]
There is no built-in benchmarking functionality built in to 86Box, because the "maximum CPU" that can be still emulated at full speed on a host system depends on the tasks and applications that run inside the guest VM. You will need to manually test the later CPU models if they still run reliably.

_To make it clear, this issue tracking system is purely for reporting bugs and requesting features. It's better to ask similar general questions on Discord or IRC (links are in the readme)._
