### ISSUE TITLE
Slowdown button

### ISSUE THREAD

**Issue by shitsux420** [86Box/86Box#2889]
**Is your feature request related to a problem? Please describe.**
Currently, 86Box runs at full speed at all times if it's able. This can be an issue with fast machines when diagnosing stuff in DOS or POST for examples as all the text flies too fast through the screen to be readable. Not all programs support a /P command or error logging functions. A slow down button that slows down the emulation % would help here. It could also be for use to "cheat" in games by making the game run slower thus giving the player a reaction advantage.

**Describe the solution you'd like**
Add a button to artificially slow down the speed of the emulation to a set amount, 50% or 25% for examples. Note that I am talking about slowing down the speed of the emulation via the emulator, not by slowing down the emulated CPU.

**Describe alternatives you've considered**
Currently I've been just pausing and praying I pause at the correct screen to view the info I want. Annoying.

**Additional context**
Disabling audio for the duration of the slow down is probably advisable as this causes audio crackling and popping issues since 86Box does not currently support audio time streaching to my knowledge.

**Comment by OBattler** [comment]
This is not doable, because at a slowdown this big tends to cause all timings to break down, so good luck even having properly working keyboard input then.

For DOS programs that don't support /P, you use | MORE instead (ie, pipe their output to the MORE command), which will make sure their output is broken up per page.

So I'm unfortunately going to close this with "can't implement".
