### ISSUE TITLE
Sound output doesn't work on Linux using current 4311 AppImage 

### ISSUE THREAD

**Issue by deividxyz** [86Box/86Box#2902]
**Describe the bug**

Using latest stable x86-64 (4311) AppImage in OpenSUSE Tumbleweed, sound doesn't work at all. 
Using previous release 4032 (3.7.1), sound works as expected.
Soundcards get detected but doesn't output any sound.

**To Reproduce**
1. Open a emulated machine, any soundcard/any type
2. BIOS beep doesn't chime, nor OS sounds

**Expected behavior**
Sound works on previous 3.7.1, 86Box-Linux-x86_64-b4032 AppImage.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] OpenSUSE Tumbleweed 20221127
 - 86Box version: [e.g. v3.7.1 build 4032; saying "Latest from Jenkins" isn't helpful]: 3.11 build 4311
 - Build information: [i.e. new/old dynarec, architecture and build type] Build 4311 x86_64, old recompiler

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

86Box config:
[86box.cfg.zip](https://github.com/86Box/86Box/files/10114084/86box.cfg.zip)

**Comment by parkerlreed** [comment]
Is the sound gain turned up in the menu? Using 4311 with pipewire on the Steam Deck and I have sound currently. 

Also is the individual stream turned up within your volume mixer?

**Comment by OBattler** [comment]
Please bisect and see which build exactly broke it. None of us can reproduce the bug, so we can't do that ourselves.

**Comment by deividxyz** [comment]
Hi! I have the gain slider at 100%. I bisected the builds and the last build that has sound working is 4135 x86_64. Build 4136 breaks sound in my Tumbleweed system.

Thanks in advance,

**Comment by deividxyz** [comment]
I've compiled 3.11 as a normal binary file and it works flawlessly with sound. Seems to be an issue with the AppImage not liking OpenSUSE.

**Comment by deividxyz** [comment]
The flatpak version 3.11 also has sound on OpenSUSE.

**Comment by acfsas** [comment]
I also have the same problem on Manjaro Linux x86_64, but I remember the first time I opened the new x86_64 AppImage. It asked me to install FluidSnyth, even though I already have it installed (version 2.3.0-2). Here are the contents of my config file, if it is of any use:

[General]
vid_renderer = qt_software
scale = 0
vid_resize = 1
sound_gain = 4
hide_status_bar = 1
hide_tool_bar = 1
kbd_req_capture = 1
window_remember = 1
force_43 = 1
video_fullscreen_first = 0
mouse_sensitivity = 1.2

[Machine]
machine = p54tp4xe
cpu_family = pentium_p54c
cpu_speed = 120000000
cpu_multi = 2
cpu_use_dynarec = 1
time_sync = local
fpu_type = internal
cpu = 5
mem_size = 65536

[Video]
gfxcard = trio64v2dx_pci
voodoo = 1

[Input devices]
mouse_type = msserial

[Sound]
fm_driver = nuked
sndcard = sbawe32
midi_device = system_midi

[Storage controllers]
hdc = internal
cassette_mode = load

[S3 Trio64 PCI (Phoenix)]
memory = 4

[Standard PS/2 Mouse]
buttons = 2

[Sound Blaster AWE32]
base = 0220
emu_base = 0620
base401 = 0330
irq = 5
dma = 1
dma16 = 5
onboard_ram = 2048
opl = 1
receive_input = 1
receive_input401 = 0

[Network]
net_01_card = pcnetpci
net_01_net_type = slirp
net_01_link = 0

[Hard disks]
hdd_01_parameters = 63, 16, 4063, 0, ide
hdd_01_fn = WINDOWS98/Windows98
hdd_01_speed = ramdisk
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 35_2hd
cdrom_01_speed = 52
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0

[Other peripherals]
postcard_enabled = 1

[AMD PCnet-PCI II #1]
mac = 58:40:88

[Microsoft Serial Mouse]
port = 0
buttons = 4

[3DFX Voodoo Graphics]
type = 2
framebuffer_memory = 2
texture_memory = 2
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 2
sli = 0
recompiler = 1

[Monitor #1]
window_coordinates = 0, 29, 1099, 985

[Monitor #2]
window_coordinates = 0, 0, 0, 0

**Comment by richardg867** [comment]
Tested openSUSE Tumbleweed (somewhat outdated 20230112 because I downloaded it then had to go do other stuff): 86Box worked fine with the ALSA fallback right out of the box. However, I did notice the system defaults to PipeWire, which we weren't using directly due to outdated libraries on our end.

@deividxyz @JKjakay and anyone else with Linux audio issues should try [build 4390](https://ci.86box.net/job/86Box/4390/) or newer, as PipeWire is now enabled and tested working. If the issue persists, please run 86Box from a terminal and paste the command line output, as that sometimes contains important audio diagnostic data.

**Comment by richardg867** [comment]
Fedora 37 also tested good with both ALSA fallback (even on build 4311) and the new PipeWire-enabled build. Manjaro 22.0.1 on the other hand has issues with ALSA fallback, but newer builds like the aforementioned 4390 work with PulseAudio (as well as PipeWire installed through `manjaro-pipewire`).

I've also sorted out some FluidSynth dependency issues since the comment by @acfsas so feel free to try that again on a newer build.

**Comment by OBattler** [comment]
I guess this can be closed then.
