### ISSUE TITLE
Mouse (input) lag

### ISSUE THREAD

**Issue by 2mg** [86Box/86Box#292]
High priority: there is a very slight delay when moving the mouse and emulated guest response.
Low priority: cursor and windows refresh at low-ish rates at 100% emulation speed and 60FPS.

**Comment by OBattler** [comment]
That's because the guest OS checks the emulated mouse's status at its own pace (and in case of bus mice, there's the additional delay caused by the timers), so there's no way to make it see host mouse changes instantly.
Also, graphics modes are seldom as fast as 60 FPS/60 Hz. For example, 1024x768x32bpp modes often tend to be 40'ish Hz, and are often also interlaced (so 43 Hz corresponds to effectively 21.5 FPS). So the low'ish refresh rate is inevitable and would have been observed on period hardware as well. We currently do not yet emulate any later graphics card with higher refresh rate.

**Comment by MoochMcGee** [comment]
Can we mark this as notabug or something and close?
