### ISSUE TITLE
[FEATURE REQUEST] XDF Floppy Format Support

### ISSUE THREAD

**Issue by PeladoFeo** [86Box/86Box#293]
Required for the floppy versions of PC DOS 7 and OS/2 Warp 3 to be fully usable on 86Box.

**Comment by MoochMcGee** [comment]
...You DO realize that IMG format XDF floppies are already supported just fine, right?

**Comment by OBattler** [comment]
Yes, XDF is already fully supported. I in fact spent a lot of time making sure XDF works exactly as it would on real media. This means that unlike on pretty much every other emulator (or virtualizer), on 86Box you actually need to use XDF.COM (which is also run automatically by PC DOS Setup) to access such images.
The only XDF variant not yet supported is 2.88 MB (3.5" 2ED) XDF, because I need surface as well as IMG dumps of real such floppies in order to know the sector layout. But 1.2 MB (5.25" 2HD) and 1.44 MB (3.5" 2HD) XDF images are already supported.

**Comment by OBattler** [comment]
This can be closed since it's a non-issue.
