### ISSUE TITLE
EGA monochrome graphics card crash

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#2944]
**Describe the bug**
I tried a game a 1988 called PC Jigaw it support several video modes ne of them is EGA 640x350x2 colors (monochrome), th text of the first screen is screwed and if start the game, it crashes when it starts to mix the pieces. Works fine on color EGA and VGA.
Note: I used the monochrome white monitor option on 86box to test the monochrome mode.

Here is the image file of the game:
[PC-Jizzaw 1988.zip](https://github.com/86Box/86Box/files/10149634/PC-Jizzaw.1988.zip)

**To Reproduce**
1. Start any VM with a 808x/286 CPU
2. change to the floppy drive at DOS prompt
3. Type JIG (the game autodetects the video modes) 
5. You'll see the screen issues on  monochrome EGA

**Screenshots**

Here is when the VM crash:
![EGA-MONO puzzle bug 001](https://user-images.githubusercontent.com/31600563/205519674-e70a9f93-57d4-4ec1-83da-04bf422caae9.png)

Here is regular color EGA:
![EGA-MONO puzzle bug 002](https://user-images.githubusercontent.com/31600563/205519723-d43aa14c-b5b9-413e-8ed7-44f21bd5c1aa.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - 86Box version: 3.11.0.4313
 - Build information: old dynarec Win32

**Additional context**
Is one of the few DOS gamea I kno,w that supports the EGA 640x350 2 colors video mode.

**Comment by TC1995** [comment]
Did this happen before?

**Comment by Fenix770** [comment]
I also found a similar bug when installing Windows 3.0 on the NCR 286 and EGA monochrome mode.
![EGA bug 3](https://user-images.githubusercontent.com/31600563/206219424-4cfba14b-135a-4879-9127-c98436a84afb.png)

**Comment by Fenix770** [comment]
Windows 3.0 seems to work fine with the 640x350 monochrome mode with  128/256 kb of RAM. But PC Jizzaw game have same issue with 128kb of RAM.

**Comment by Fenix770** [comment]
I also tested SIMCGA 4.2E with EGA monochrome. It emulates CGA video modes in a same way that it does on the Hercules card.
Only SIMCGA 4.2/4.2D/4.2E, supports the Hercles monochrome. 
This screenshot was taken form the Tetris game with EGA monochrome with CGA graphics with SIMCGA and Kawase 0 sharder.

Notice the black line on the right of the screen:
![Testris Black line bugpng](https://user-images.githubusercontent.com/31600563/206244380-05f5e685-bca6-40a2-ba01-7ad2a8496d5d.png)

**Comment by Fenix770** [comment]
I found a last game that supports the EGA monochrome natively:
This game crash with a black screen and a blinking crusor when tipying MAJ -L to force the EGA mono mode with EGA monochrome card even with 256k. 

The EGA mono mode works fine on OTI-67 VGA if I force the EGA mono mode with MAJ-L.

Here are screenshots of EGA color and monochrome mode taken from the OTI-67 card.
![EGA color on OTI-67 VGApng](https://user-images.githubusercontent.com/31600563/206287019-0bc6bb5e-ed89-476e-83ce-63c98a38923a.png)

![EGA mono on OTI-67 VGA](https://user-images.githubusercontent.com/31600563/206287028-f00437c6-6783-43ce-ae5e-dbfd0261a9d5.png)

So the game works fine, the issue is with the EGA card with MDA display.

**Comment by iamgreaser** [comment]
Short version: The exact issue pertains to how *both* 64KB 640x350 modes work, which involves Odd/Even mode and Word Mode to use 2 bits per pixel instead of 4.
I am using commit b5f069248323023231087956805d603f1ac1b4b4 from 2023-03-10T07:00:01+0100.

Been neck-deep in EGA docs lately (ESPECIALLY the official schematic!) and this is probably going to be a good step towards getting EGA emulation accurate. Part of what got me interested was trying to get my head around Odd/Even mode and what enabling/disabling it in different parts actually does.

> PD: I use 64kb of video RAM. As I think it should be enought for monochrome video modes.

It uses 2 bits per pixel when you have 64KB, and 4 bits per pixel when you have 128KB/256KB.

Both 640x350 BIOS modes do something really interesting when you only have 64 KB and I'm trying to get my head around this. You don't even need monochrome for this - just give yourself an EGA with 64KB of RAM and a monitor that can handle the relevant 640x350 mode you want to try, and 86Box will break in the same way in both cases.

At a basic level, here's what the difference is from what I can scrape together right now from IBM's video mode tables (using the terms "64K" vs "128K+" for the 640x350 modes ONLY):
- The bitplane shift registers in the Graphics Controllers are latched on every character clock in 128K+, but every 2 character clocks in 64K.
- The CRTC increases the memory address counter every character clock in 128K+, but every 2 character clocks in 64K.
- Odd/Even mode is fully enabled for 64K, and fully disabled for 128K.
- The CRTC is set to Word Mode (and CRTC address bit A15 is shifted into address bit A0) for 64K, and set to Byte Mode for 128K+.

Odd/Even mode affects CPU accesses, while Word Mode affects CRTC accesses.

Here's what Word Mode roughly does (CRTC only):
- Shifts all CRTC address bits left by 1, while shifting either bit A13 or bit A15 into the A0 position.

Here's what Odd/Even mode roughly does (CPU only):
- (3CE/06/b1=1) Replaces bit A0 with a higher-level bit (A14 or A16) or the PGSEL bit (0x3C2, bit 5) depending on whether the memory map is the A000:128K mapping or not, and whether we're set to 64KB mode or not.
- (3C4/04/b2=0) Uses the original A0 bit from the CPU to mask the planes written to (and read from?) - if 0, we access Planes 0,2 only; if 1, we access Planes 1,3 only.
- (3CE/05/b4=1) One other thing, but I haven't worked this one out... maybe it chains each pair of planes together? I don't know yet, and I would love to get my hands on the actual hardware to find out what this really does. It probably also masks out plane outputs 1,3, leaving only planes 0,2 going to the Attribute Controller to be displayed, except when it's put in the CGA shift mode in the same register.

I've been using GW-BASIC to test the video modes (SCREEN 9 for 2bpp colour, SCREEN 10 for monochrome). 86Box has no issues with the 128K+ variants, but the 64K variant shows "OO" instead of "Ok" (and groups of 8 pixels are doubled), and the F-key help text at the bottom of the screen doesn't show.

And just in case you thought we needed more screenshots (using an amber monitor here):
![image](https://user-images.githubusercontent.com/138113/226213346-c06c1f74-7d70-413c-b55e-411057baee13.png)

64K:
![image](https://user-images.githubusercontent.com/138113/226213526-d7fb7a5d-68d6-4e94-aa6f-dd699240cb30.png)

128K+ (the program ends up drawing over the F-key help text bar, hence why it's not visible here):
![image](https://user-images.githubusercontent.com/138113/226213520-e6154dbf-5bad-4f6a-b592-32195024517a.png)

**Comment by iamgreaser** [comment]
OK, this is from a rewrite of the EGA renderer I started earlier today, and I've managed to get this to work properly. This is GW-BASIC's SCREEN 9 which is the 640x350 colour mode, and for 64KB it's 2bpp. (SCREEN 10 also works if I use a monochrome monitor.)

![image](https://user-images.githubusercontent.com/138113/226282175-f2ea21ab-f99e-48ff-abc8-c88372c4488f.png)

It will require a correct implementation of Odd/Even mode, which affects A0 quite differently from what you'd think - here's how it actually maps when Graphics register 6 bit 1 is set to 1 (according to the schematic):
- 128K+ installed, anything other than the 128KB A000 mapping: A0 is set to the opposite of bit 5 of 0x3C2 (most docs I've seen get this backwards, although both IBM and C&T ends up stating it wrong in the description while later on showing the correct inverted behaviour in another way - IBM in the schematic, C&T in a table)
- 128K+ installed, 128KB A000 mapping: A0 is set to A16 before A16 is masked off
- 64K installed, anything other than the 128KB A000 mapping: A0 is set to A14
- 64K installed, 128KB A000 mapping: A0 is set to A0

It will also require shifting Plane 1 into Plane 0 (and Plane 3 into Plane 2) - I'm actually doing a rotate through the two for convenience, but the actual behaviour needs to be tested on real hardware which I don't have. If you don't do this, you get the repeated 8-pixel-wide columns that you're seeing in these screenshots.

Another note is the CRTC Word Mode always uses MA13 on an unexpanded 64KB EGA. But if a memory expansion is installed (128KB+), CRTC reg 0x17 bit 5 does allow one to use MA15.
It seems that sequencer reg 0x04 bit 1, if set, will ignore CPU address bits A14 and A15 when attempting to access VRAM (well OK, what it seems to actually do is force the use of ~ACAS0 and ~BCAS0, instead of the ~(A|B)CAS[1-3], but it's easier to think in terms of address bits here and the 82C43x chipset does use address bits). It also seems that this needs to be emulated for this to work.

If anyone has an actual EGA and is willing to test some hypotheses, I can be found on the 86Box IRC channel as GreaseMonkey. I'd love to see the EGA get emulated accurately. (Partly because there may be some neat "mixed modes" involving stuff like Odd/Even mode and Alphanumeric Mode not being applied everywhere.)

**Comment by iamgreaser** [comment]
This was addressed in PR #3217 .

PC-Jigsaw monochrome now works (tested on 64K, 128K, 256K):
![image](https://user-images.githubusercontent.com/138113/226482803-20a03974-cfc7-43f7-87ca-0cdf4898d88a.png)

And Windows 3.0a (tested on 64K only - screenshot accidentally had something over the top of it so I've cut it out w/ red, but it does look normal):
![image](https://user-images.githubusercontent.com/138113/226484385-fe09e204-ba45-4fdb-b0e0-325a80df9d24.png)

**Comment by OBattler** [comment]
I'm closing this then, a separate issue can be opened for Mahjongg.
