### ISSUE TITLE
libgs not detected on Arch Linux

### ISSUE THREAD

**Issue by einstein95** [86Box/86Box#2996]
Was having an issue where Ghostscript wasn't being detected despite the `extra/ghostscript` package being installed. Found the cause is this line: https://github.com/86Box/86Box/blob/38b9d4e9fabd6f9f9329046cab24941f1cb6932b/src/printer/prt_ps.c#L54

Arch has v10.0.0 of Ghostscript so the lib files are like this
```
lrwxrwxrwx 1 root root  14 Sep 23 04:55 /usr/lib/libgs.so -> libgs.so.10.00
lrwxrwxrwx 1 root root  14 Sep 23 04:55 /usr/lib/libgs.so.10 -> libgs.so.10.00
-rwxr-xr-x 1 root root 22M Sep 23 04:55 /usr/lib/libgs.so.10.00
```

Changing the line to this should be fine, but I can see that at least CentOS wants `libgs.so.9`
```cpp
 #    define PATH_GHOSTSCRIPT_DLL "libgs.so" 
```

**Comment by dhrdlicka** [comment]
Maybe it would be best to just have the option to link against libgs rather than load it dynamically.

**Comment by sharkcz** [comment]
There might be legal reasons for dlopen()-ing `libgs.so`, so be careful.

Defaulting to `libgs.so` would be wrong, because it's the development symlink, not the runtime library. The whole Fedora/RHEL/... ecosystem seems to be on libgs major version 9 so far.

**Comment by dhrdlicka** [comment]
The reason is rather simple, the code was originally written for Windows and we prefer to dynamically load libraries there to make sure that `86Box.exe` can run on its own, without any dependencies.

Given that it's not as common to handle standalone executables on Linux as it is on Windows, it makes more sense to just not `dlopen` it and simply link against it the regular way as I mentioned above.

**Comment by CoelacanthusHex** [comment]
If we can't link libgs directly on Linux, it is another choice to add a build option to control dlopen which library file.
