### ISSUE TITLE
IBM PC Xenix

### ISSUE THREAD

**Issue by ArtiomWin** [86Box/86Box#309]
Issues with IBM PC Xenix (both 1.00 and 2.00):

1. badtrack app incorrectly recognizes hard drive and "finds" too many bad tracks
2. After loading xenix.fd emulated IBM PC AT freezes at all

P.S. That is not SCO Xenix, but OEM version for IBM PC AT that was made available couple of weeks ago.
![20180821_184027](https://user-images.githubusercontent.com/31134876/44412883-a2bdc280-a572-11e8-911c-3cc8735053d6.png)
![20180821_184116](https://user-images.githubusercontent.com/31134876/44412884-a3565900-a572-11e8-8bda-5d59d26c107b.png)

**Comment by waltje** [comment]
It tried to use the drive as Type15, which is invalid.

What is the configuration(-file) you are using, or, rather, on
what kind of controller and drive are you installing?

--waltje

--------------------------------------------
On Tue, 8/21/18, ArtiomWin <notifications@github.com> wrote:

 Subject: [86Box/86Box] IBM PC Xenix (#309)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Date: Tuesday, August 21, 2018, 11:49 AM
 
 Issues with IBM PC Xenix (both
 1.00 and 2.00):
 
 badtrack app incorrectly recognizes hard drive and
 "finds" too many bad tracks
 After loading xenix.fd emulated IBM PC AT freezes at
 all
 
 P.S. That is not SCO Xenix, but OEM version for IBM PC AT
 that was made available couple of weeks ago.
 
 
 
 
 
 —
 You are receiving this because you are subscribed to this
 thread.
 Reply to this email directly, view it on
 GitHub, or mute
 the thread.

**Comment by OBattler** [comment]
This is floppy drives, if I understand correctly. ArtiomWin probably didn't run the IBM AT setup diskette before doing this, resulting in the NVR having invalid floppy drive types set.

**Comment by ArtiomWin** [comment]
Here's the config.
[Xenix.zip](https://github.com/86Box/86Box/files/2309153/Xenix.zip)

**Comment by waltje** [comment]
Hi,

OK, so you are using an ST-225 (20MB, 615/4/17) disk, which is IBM type 2.

Did you set up the AT using its Setup Diskette, and did you tell it that Drive0
has type2, and Drive1 has type0 (== none) ?

The AT did not have "autoconfig" stuff, you had to do that manually using the
AT setup/diagnostics diskette.

Fred
--------------------------------------------
On Wed, 8/22/18, ArtiomWin <notifications@github.com> wrote:

 Subject: Re: [86Box/86Box] IBM PC Xenix (#309)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Fred N. van Kempen" <decwiz@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Wednesday, August 22, 2018, 2:43 AM
 
 Here's the
 config.
 
 Xenix.zip
 
 —
 You are receiving this because you
 commented.
 Reply to this
 email directly, view
 it on GitHub, or mute
 the thread.

**Comment by waltje** [comment]
Hmm... I do see you have ATDG 2.07 mounted, so you probably did add it.

That I would need to test here....

--fred

--------------------------------------------
On Wed, 8/22/18, ArtiomWin <notifications@github.com> wrote:

 Subject: Re: [86Box/86Box] IBM PC Xenix (#309)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Fred N. van Kempen" <decwiz@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Wednesday, August 22, 2018, 2:43 AM
 
 Here's the
 config.
 
 Xenix.zip
 
 —
 You are receiving this because you
 commented.
 Reply to this
 email directly, view
 it on GitHub, or mute
 the thread.

**Comment by waltje** [comment]
In the Settings menu, turn off Time Sync Enable.
Reboot with the ATDG disk, and configure the system - that should work now.
Reboot, turn Sync back on, all should be well.

(I thought I replied to this earlier, but apparently that (email) reply never made it !

**Comment by ArtiomWin** [comment]
I've turned off time sync. IBM PC AT diagnostic diskette ver. 2.07 still have same issues, but version 1.02 have configured successfully. Thanks.
