### ISSUE TITLE
Is NEAT(sx) chipset emulation  of AMI 286 and DTK 386SX implemented?

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#312]
Hello!

I want to ask you if the AMI 286 NEAT chipset is emulated, and if it is, how can I Configure it in CMOS?
Because I would like to test the EMS memory emulation. 
The BIOS of the machine has a lot of technical options that I don't understand very well.
The DTK 386sx had a NEATsx chip, I don't know if it's emulated, but it is a lot easier to configure in BIOS.
It only requires to specify the amount of EMS memory. I also have a NEAT EMS device driver version 1.5 and another which is an evaluation copy version 1.52

Thanks!

**Comment by OBattler** [comment]
It's not yet, waltje is working on that for varcem, and it's going to be ported 86Box when he's done.

**Comment by OBattler** [comment]
BTW, Fenix770, let me inform you of exactly what went on between PCem and 86Box:
Going to respond here since I'm banned from the PCem forum:

>> But in general, the entire 'fork' experience was very unpleasant,
Only because Sarah kept throwing tantrums, including on my own IRC channel.
Let me go fully public with what led to the second forking:
- I was contributing patches to PCem and they were taking too log to be processed - there's still patches of mine from 2015 that haven't been touched;
- The above is not a problem per se, but it led to my changes to the code accumulating to the point they were massive and difficult to split;
- I asked Sarah to coordinate changes with me so I wouldn't have to spend extra days merging your large code changes with my own;
- Sarah told me to "just use hg diff" which I told you won't work as my changes were big enough that hg diff was failing to apply them cleanly;
- Even then I didn't fork, I wanted to keep trying to contribute to you but then a lot of people on my IRC net started telling me to fork;
- It took quite some time between them first telling me to fork and me finally agreeing to do so, and I felt bad about it because I knew you wouldn't like it and I wanted to avoid renewed conflict with Sarah;
- Even after forking, I tried to salvage our relationship by thinking of how best to contribute to Sarah and not mentioning 86Box on Sarah's forum so as not to upset to;
- When that guy last year decided to start passing logs to and from Sarah in his obsession to try to reunify the two projects, I actually told him not to as he'd just make things worse, he didn't listen;
- By then, Sarah was also falsely accusing me of deliberate transphobia over two accidental misgenderings, and tag-teaming with leilei to berate me over my views regarding compiler versions and such;
- Sarah also became more and more hostile towards me for not contributing [enough] to PCem, even though there were patches of mine from 2015 that were still untouched;
- Then Sarah accused me of deliberately low-level attacking you over a poorly worded post I made;
- Then finally the dnsk2 incident led to me being banned.

So in short, I was contributing to Sarah, I asked to more coordination, achieved nothing, decided to keep contributing to Sarah, was convinced by my friends on IRC to reluctantly fork, tried to keep things calm by keeping my fork outside her forum, she threw a tantrum on my own IRC channel, some things happened that she interpreted as deliberately wrongdoings on my part even though they were not, and she kept demanding me to contribute more even though several of my patches from 2015-16 were still waiting to be processed, ultimately i was banned over a pretty stupid thing I do realize I shouldn't have done.
She has showed a complete inability to handle things civilly, then ultimately banned me for being unable to be civil. And now, me and my fork are the reason for "pain".

>> and there's a reason everyone involved (with the exception of SA1988, who has been reasonably well behaved since then) got banned from this forum.
From what I know, all 86Box people who got banned from her forum, got banned for reasons entirely unrelated to the forking:
- Kaz was banned for bashing Sarah on my IRC channel, that I myself didn't like him doing;
- Alegend45 (mooch) was banned for bad behavior on her forum;
- I was banned for "slagging off dns2k" by pointing out he has a history of posting questionable PCem patches on the RetroROMs forum, to which he himself admitted, though I do admit that was inappropriate of me to do.

>> Since when? I'm a human being, not a machine.
If Sarah wants people to be considerate of that and of her feelings, she needs to start showing the same consideration to other people and their feelings.

Well, now you know my side of the story. I'm sorry for bringing this up here, but I had to, given Sarah and leilei were bashing me behind my back on their forum.

**Comment by Fenix770** [comment]
Sorry!

I did not know. I regret to know about that issue.

**Comment by OBattler** [comment]
Nah, you're not at fault here. You just liked a feature of one emulator and suggested it be ported to PCem. It's Sarah and lelilei that reacted inappropriately since they can't get over the fact 86Box exists. :p

In any case, 86Box now has the improved NEAT emulation from VARCem. :p
