### ISSUE TITLE
Compilation error on Ubuntu 18.10

### ISSUE THREAD

**Issue by glasen** [86Box/86Box#325]
Hi,

i'm trying to compile 86Box on my Ubuntu 18.10 installation. The compilation fails with the following error:

```
isartc.c
isartc.c: In function ‘mm67_time_get’:
isartc.c:292:7: error: dereferencing pointer to incomplete type ‘struct tm’
     tm->tm_sec = RTC_DCB(regs[MM67_SEC]);
       ^~
isartc.c: In function ‘mm67_start’:
isartc.c:351:15: error: storage size of ‘tm’ isn’t known
     struct tm tm;
               ^~
isartc.c:351:15: warning: unused variable ‘tm’ [-Wunused-variable]
make: *** [win/Makefile.mingw:600: isartc.o] Fehler 1
```
Ubuntu 18.10 uses GCC version 8.2

**Comment by OBattler** [comment]
Right now the emulator doesn't even have a Linux port, it's in the plans but given the fact 86Box is developed by me and another developer (with others sporadically contributing), and neither me nor the other guy has much experience in porting things to Linux (other than command-line applications), it's going to take a while. :p
In any case, the problem you're reporting seems to be because isartc.c doesn't #include <time.h>. I just made a commit fixing this.

**Comment by OBattler** [comment]
SDL is only used as a renderer (and it's still unfinished at that), the UI is written using the native Win32 API, so a Linux port is going to require a port of the UI to something like wxWidgets or QT.

**Comment by OBattler** [comment]
The question has been answered and the conversation about the Linux port can be continued in the older issue, so I'm closing this.
