### ISSUE TITLE
[Unverified] Bare metal Hydro Thunder crashes 86Box.

### ISSUE THREAD

**Issue by FavoritoHJS** [86Box/86Box#3252]
**Describe the bug**

According to Tech Tangents, running Hydro Thunder in bare metal appears to crash both PCEm and 86Box -- but only on Linux, Windows appears to be fine. See: https://youtu.be/Dy6Uvyl0lwo?t=767

I'm guessing some compiler jank is ocurring here, where MSVC doesn't overoptimize something that GCC/Clang/whatever does, so the former works and the latter trips itself up in undefined behavior.

**Comment by OBattler** [comment]
We use MingW GCC (with Clang as an option) on Windows as well, we do not support MSVC at all. The same goes for PCem.

It is to be noted that on Linux, it was most likely a 64-bit binary of both emulators, but 32-bit on Windows.

In any case, this is a CANTFIX - unless it happens to be the same crash I fixed recently by allocating 16 extra bytes of RAM because of some dynarec behavior, in which case it's even fixed.
