### ISSUE TITLE
[Request] Support for Award BIOS 3.03

### ISSUE THREAD

**Issue by Mako88** [86Box/86Box#334]
Hello,

I was just wondering if it might be possible to add support for this older Award BIOS: http://minuszerodegrees.net/at_clone_bios/Award%20286%20Modular%20BIOS%20Version%203.03%20-%20BIOS%20ROM.zip

It was fairly popular for off-brand IBM clones.

Thanks!

**Comment by OBattler** [comment]
What machine is that of? What chipset does it use?

**Comment by Mako88** [comment]
I have it on an EasyData 286. The motherboard is a Suntac 286-B. The site that I linked to has the following information:

BIOS source | Motherboard:  Everex EV-1815
Supplier | SomeGuy at the Vintage Computer Forums, MAY17
BIOS chip type | 27128       (quantity: 2)
BIOS contains the strings | "286 Modular BIOS Version 3.03" and "Award Software Inc."
Comment | ODD chip in socket U108, and labelled '23C15'EVEN chip in socket U109, and labelled '23C16'
BIOS download | Award 286 Modular BIOS Version 3.03 - BIOS ROM.zip

Let me know if you need anything else!

**Comment by waltje** [comment]
The important question here is: what were the "main chips" on the motherboard
that this BIOS was done for?  The function of the BIOS was to initialize, and work
with, the various chips on a board, so that the operation (DOS et al) did not have
to.

So, the BIOS is the easy part... now find the proper documentation and it can be done! :)

Cheers!

--------------------------------------------
On Sun, 10/28/18, Mako88 <notifications@github.com> wrote:

 Subject: Re: [86Box/86Box] [Request] Support for Award BIOS 3.03 (#334)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Date: Sunday, October 28, 2018, 12:54 AM
 
 I have it on an
 EasyData 286. The motherboard is a Suntac 286-B. The site
 that I linked to has the following information:
 BIOS source | Motherboard:  Everex EV-1815
 
 Supplier | SomeGuy at the Vintage Computer Forums, MAY17
 
 BIOS chip type | 27128       (quantity: 2)
 
 BIOS contains the strings | "286 Modular BIOS Version
 3.03" and "Award Software Inc."
 
 Comment | ODD chip in socket U108, and labelled
 '23C15'EVEN chip in socket U109, and labelled
 '23C16'
 
 BIOS download | Award 286 Modular BIOS Version 3.03 - BIOS
 ROM.zip
 Let me know if you need anything else!
 
 —
 You are
 receiving this because you are subscribed to this thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by Mako88** [comment]
They're Suntac chips:
ST62C006: http://www.datasheet-pdf.com/PDF/ST62C006-Datasheet-GSTechnology-530403
and
ST62BC001-B
ST62BC002-B
ST62BC003-B
ST62BC004-B
ST62BC005-B

I'm googling around to find the datasheets on them. I'll post links when/if I find them. Thanks!

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.

**Comment by OBattler** [comment]
Effectively fulfilled by the Hyundai Super-286C - Award 3.02j.
