### ISSUE TITLE
PCjr doesn't support 64K RAM

### ISSUE THREAD

**Issue by anikom15** [86Box/86Box#3349]
**Describe the bug**
The minimum RAM allowed for PCjr is 128K, but a 64K option was available.

**To Reproduce**
Set memory in settings

**Expected behavior**
64K RAM should be the minimum, according to https://oldcomputers.net/ibm-pcjr.html

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 86Box version: v3.11 build 4311
 - Build information: Release version, 64-bit

**Comment by TC1995** [comment]
You can use the nightly builds and the corresponding 32-bit version of the binary.

**Comment by cartifanwlr** [comment]
> You can use the nightly builds and the corresponding 32-bit version of the binary.

That does not have to do with anything here. It's something at the configuration of the PCjr, where we should normally start with 64, but we start with 128. (Turns out we also do 256, 384 all the way to 640 here, which I have no idea if it is supported in the PCjr.)

**Comment by TC1995** [comment]
I meant if the 64k option was added in later builds than 3.11.

**Comment by cartifanwlr** [comment]
It wasn't. I'm at the latest nightly build and I can't get it down to 64.

**Comment by TC1995** [comment]
> > You can use the nightly builds and the corresponding 32-bit version of the binary.
> 
> Do you mean this is fixed? If so, I can close. I prefer to use release version when possible.

"Release version" is just a label for builds.

**Comment by jriwanek** [comment]
> I meant if the 64k option was added in later builds than 3.11.

Current source code.
        .ram = {
            .min = 128,
            .max = 640,
            .step = 128
        },

I'll put together a fix when I've finished my morning stuffs

**Comment by jriwanek** [comment]
Okay, so that's annoying, our code doesn't account for the possibility that the pcjr could have 64k and fails, this is gonna take a touch longer than I expected for a fix

**Comment by fmillion** [comment]
> According to here, the maximum is 512K: https://www.atarimagazines.com/compute/issue58/pcjr_memory.html .

There were actually a few different ways to expand the PCjr up to 640K, and even beyond. I personally owned a PCjr with some hardware from a defunct company called PC Enterprises. They sold a configurable 1MB expansion board that could map memory pretty much anywhere you wanted it, bringing conventional DOS RAM up to 736K and the remainder (whatever you didn't need) could become a ramdisk, or I believe there were even drivers to make it work as EMS.

IIRC, one of the major issues with the PCjr was that the video RAM was actually mapped into the space right at 128K, so you couldn't just expand the memory by sticking some more RAM there. Instead you needed software drivers which would move the video RAM up to where it "belongs" for a CGA system. Many tools existed, a common one being "JRCONFIG.SYS" which supported this along with a bunch of other tweaks and mods to improve PCjr compatibility. 

I wish I still had my old PCjr, since I had a ton of expansion cards for it (a TMC850jr SCSI adapter, their "Display Master" which enabled EGA graphics, a "Game Master" which provided Sound Blaster and Adlib support, etc.) I'd have loved to extract the ROMs from the cards and help with implementing some of this rare hardware into 86box, but sadly that machine is long gone... :(

**Comment by jriwanek** [comment]
64k base not yet implemented, but 64k *steps* is now added, I have reason to believe that barring the initial 64/128k configuration it actually supports 32k steps in the BIOS, but I'd need to play more to be sure.

Thanks btw for the additional info, this issue is added to my work queue now. (:

**Comment by fmillion** [comment]
The original IBM PC shipped in two configs: 64K without a floppy drive and
128K with one. If 64K RAM becomes supported maybe a no-floppy configuration
will also work. (Can't recall, does 86Box support the cartridge slots? On a
64K model it was expected you would use cartridges or Caasette BASIC.)

The 128K model included a proprietary 64K RAM expander card in an internal
dedicated slot. The 64K base RAM is on the motherboard itself.

**Comment by OBattler** [comment]
This is now fixed - the PCjr now correctly supports 64 kB of RAM.
