### ISSUE TITLE
[Feature request] Can 86Box emulate a 9/24 pin printer?

### ISSUE THREAD

**Issue by coolhaken** [86Box/86Box#335]
Hi,
There are many old apps (and some old games) need a printer for output.
Can 86Box emulate a 9/24 pin printer and send it's output to a .png image ?

**Comment by daviunic** [comment]
Interesting idea.

**Comment by waltje** [comment]
Already implemented in VARCem, just take that.  I sent obat the fonts and sample outputs.

**Comment by coolhaken** [comment]
I tried the 11/3/2018 version of VARCem, but it seems can't print graphics data.
It hangs while runing "TYPE readme.doc > PRN:" under ETEN 24x24 font environment.
Besides that, a pgm image is much large than a png image ...

**Comment by waltje** [comment]
I indeed have not tried graphics stuff yet, too busy.  I added the printers to the current
codebase to have it tested more.  I can send you a more recent version if you want.

Also, it will generate PNG _if_ you have libpng16.dll in the exe folder.

--fred

--------------------------------------------
On Sun, 11/4/18, coolhaken <notifications@github.com> wrote:

 Subject: Re: [86Box/86Box] [Feature request] Can 86Box emulate a 9/24 pin printer? (#335)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Fred N. van Kempen" <decwiz@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Sunday, November 4, 2018, 1:33 AM
 
 I tried the 11/3/2018
 version of VARCem, but it seems can't print graphics
 data.
 
 It hangs while runing "TYPE readme.doc > PRN:"
 under ETEN 24x24 font environment.
 
 Besides that, a pgm image is much large than a png image
 ...
 
 —
 You are receiving this because you
 commented.
 Reply to this
 email directly, view
 it on GitHub, or mute
 the thread.

**Comment by waltje** [comment]
See attached files.

--fred

--------------------------------------------
On Sun, 11/4/18, Fred van Kempen <decwiz@yahoo.com> wrote:

 Subject: Re: [86Box/86Box] [Feature request] Can 86Box emulate a 9/24 pin printer? (#335)
 To: "86Box/86Box" <86Box@noreply.github.com>, "86Box/86Box" <reply@reply.github.com>
 Cc: "Fred N. van Kempen" <decwiz@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Sunday, November 4, 2018, 2:59 AM
 
 I indeed have not tried graphics stuff yet,
 too busy.  I added the printers to the current
 codebase to have it tested more. 
 I can send you a more recent version if you want.
 
 Also, it will generate PNG _if_ you
 have libpng16.dll in the exe folder.
 
 --fred
 
 --------------------------------------------
 On Sun, 11/4/18, coolhaken <notifications@github.com>
 wrote:
 
  Subject: Re: [86Box/86Box] [Feature
 request] Can 86Box emulate a 9/24 pin printer? (#335)
  To: "86Box/86Box" <86Box@noreply.github.com>
  Cc: "Fred N. van Kempen" <decwiz@yahoo.com>,
 "Comment" <comment@noreply.github.com>
  Date: Sunday, November 4, 2018, 1:33
 AM
  
  I tried the 11/3/2018
  version of VARCem, but it seems can't
 print graphics
  data.
  
  It hangs while runing "TYPE readme.doc
 > PRN:"
  under ETEN 24x24 font environment.
  
  Besides that, a pgm image is much
 large than a png image
  ...
  
  —
  You are receiving this because you
  commented.
  Reply to this
  email directly, view
  it on GitHub, or mute
  the thread.
  

 Volume in drive H is WALTJE     
 Volume Serial Number is 0951-1F03
 Directory of H:\SRC\EPSON

.            <DIR>     09-02-18   4:28p
..           <DIR>     09-02-18   4:28p
MAKEFILE           935 09-02-18   4:41p
GETOPT   C        1672 08-30-18   1:01a
MAIN     C        1298 09-02-18   5:04p
GETOPT   H         765 08-30-18   1:01a
GLOBAL   H         325 09-02-18   5:05p
EPSON    C        2394 09-02-18   5:42p
        8 file(s)       7389 bytes
                       88064 bytes free

**Comment by coolhaken** [comment]
Thanks for your reply.
If you do make a new version about this feature, I am glad to  help doing some test job.
Please put it on VARCem's site, I (and many other people) will try it. ;)

Since I opened this issue here, I hope this feature can also implemented in 86Box.

BTW, some retro apps only work with 9 pin printer, e.g. "The Print Shop".
So I think the printer emulation may need some configurable options.

**Comment by coolhaken** [comment]
I noticed that 86Box #1823 added the printer emulation.
However, some machine doesn't work for me and 86Box always say unable to initialize FluidSynth.
Maybe I need a new romset.
Then I set machine to Award 486 clone and try to print something, but nothing happened.
E.g. I tried "DIR > PRN:" under DOS 6 times.

**Comment by OBattler** [comment]
You need the FreeType .DLL and a few others. Without them, the ESC/P printer won't work. But wait for the next commit anyway, which is going to fix a lot of things, including graphics printing (in ESC/P mode - the ESC/P 2 Print Raster Graphics command is not yet implemented).
