### ISSUE TITLE
can't connect to netware network

### ISSUE THREAD

**Issue by 0xh3LL0** [86Box/86Box#3417]
**Describe the bug**
win 98 on 86box can not connect to netware network,
while tried with another sollution, it can connect

**To Reproduce**
start windows 98 > start > settings > control panel > network > client for netware network > properties > general > prefered server > my server name should appear here

**Expected behavior**
it should connect to netware

**Screenshots**
![WIN98](https://github.com/86Box/86Box/assets/23132217/0e01bda7-6862-4b20-9ab4-2a93efa200f6)

**Desktop (please complete the following information):**
 - OS: win 10 x64 1607 ltsb
 - 86Box version: 4311
 - Build information: 
 Machine: socket 7 single voltage, asus p/i-p54tp4xe, intel pentium overdrive mmx, speed 200, memory 128
 Display: pci 3dfx voodoo3 3000
 Input: standart ps/2 mouse
 Sound: sound blaster pro v2, use float32 sound
 Network: pci realtek rtl8029as
 Storage: pci ide controller
 Harddisk: ide 509mb ramdisk
 Floppy: 3.5 1.44m
 CD ROM: atapi 72x
 
 
 

**Additional context**
Add any other context about the problem here. If you are using an Optimized build, make sure to try the regular build too before filing a bug report!

**Comment by cold-brewed** [comment]
Looks like you're using 3.11. There were some fixes that went in recently that adressed issues in all the dp8390-based cards (ne2000, rtl8029, etc.) when using netware. After those fixes I've been able to connect DOS and win 98 systems to a netware 3.12 server.

Download the latest version [here](https://ci.86box.net/job/86Box/) and try it again.

Are you using pcap to connect to an existing netware server?

**Comment by 0xh3LL0** [comment]
no luck

**Comment by 0xh3LL0** [comment]
btw here is the screen from virtualbox
![Screenshot8](https://github.com/86Box/86Box/assets/23132217/72fce833-1655-4732-86b4-912665d06fd0)

**Comment by 0xh3LL0** [comment]
i create 2nd vm with the same setting from 86box official channel
https://www.youtube.com/watch?v=ckGNRjgdrnI
but, its just same.

**Comment by cold-brewed** [comment]
How are you connecting to the netware server? Are you using PCAP?

Could you please upload your vm configuration here?

**Comment by 0xh3LL0** [comment]
i dont remember setting something called pcap

where is the config file?

**Comment by cold-brewed** [comment]
Head over to Settings -> Network -> Mode. Can you tell me what mode you're using?

This is important because only certain options will work for a Netware server that uses IPX. For example, netware will *not* work with slirp.

The config file is `86box.cfg` and is located in the directory that has your hard drive image.

**Comment by 0xh3LL0** [comment]
yes, it slirp

[86box.zip](https://github.com/86Box/86Box/files/11844283/86box.zip)

**Comment by 0xh3LL0** [comment]
i tried to change it to null driver (which not available in 4311) instead of slirp but still not connected

**Comment by cold-brewed** [comment]
Null driver will not work for any external communication because all packets sent from the guest are dropped.

SLiRP will also **not** work with netware. I suggest reading up on the documentation [here](https://86box.readthedocs.io/en/latest/hardware/network.html) as it covers why Netware will not work on SLiRP due to the use of IPX.

Your only option is to use PCAP to allow IPX packets through. And even then, (also covered in the documentation) that will only work on hard wired ethernet *or* a local private network interface (the netware vm would also have to be on that same interface).

The documentation should give you a sense of your options. Note this is can be a challenging topic (the networking of multiple VMs using different technologies), especially when you are mixing programs (like 86Box and virtualbox).

For example, I don't have any way of knowing if your virtualbox vm has networking configured properly either. Even if you had 86Box configured properly, if the virtualbox vm is not then it will never work.

If you'd like to run the netware server and client in 86box I'd suggest reading [this section](https://86box.readthedocs.io/en/latest/hardware/network.html#private-pcap-network) on creating a private pcap network.

**Comment by 0xh3LL0** [comment]
my netware run on **real** hardware (not vm)
virtualbox auto-detect the best setting when i type "windows 98", i change **nothing** but ram to 128, and it can connect to netware out of the box.

i read the documentation but i'm not so techy person so i guess i'll stick with virtualbox for now.

thank you.

**Comment by cold-brewed** [comment]
> yes, it slirp
> my netware run on real hardware

Okay, this makes more sense now. Netware requires IPX but slirp can only do TCP and UDP.

In order to make 86Box (on windows) work with netware you will have to use the PCAP mode in network settings. 

There are some limitations to PCAP mode: For example, if your host system is on wifi, PCAP will not work properly because it cannot capture the packets. 

However, if you are on a wired ethernet connection you should be able to 1) Use PCAP mode in 86box and 2) Select the wired ethernet interface to be used with PCAP. Then you should be able to talk with the physical netware system. 

Note that Virtualbox does not have these limitations because it installs network interfaces at the OS level, unlike 86box.

**Comment by lemondrops** [comment]
To add to the above: for PCap to be available in 86Box on Windows, you need to install either [Npcap](https://npcap.com/) **(check the "Install in WinPcap compatible mode" checkbox during installation)** or [Win10Pcap](http://www.win10pcap.org/download/) on your host system.

**Comment by OBattler** [comment]
I guess this can be closed then.
