### ISSUE TITLE
[8086] Toshiba T1200 keyboard not working when mouse driver is loaded

### ISSUE THREAD

**Issue by maximus105** [86Box/86Box#3501]
**Describe the bug**
On machine [8086] Toshiba T1200 (also possible on other 8086 machines) the keyboard does not work in Goody, Living, Mission when a Microsoft Serial Mouse is connected and the CuteMouse mouse driver is loaded. This bug appeared in build 4438 and persists until the latest build. In build 4436 everything works fine.

**To Reproduce**
1. Start the attached machine [8086] Toshiba T1200.
2. Run Goody, Living, Mission games in C:\Games.
3. Goody, Living, Mission games freeze immediately when Space is pressed. Also, in these games, the Q, A, O, P, Space, etc. buttons do not work.

**Expected behavior**
On machine [8086] Toshiba T1200, the keyboard in Goody, Living, Mission games should work properly when a Microsoft Serial Mouse is connected and the CuteMouse mouse driver is loaded.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 v22H2
 - 86Box v4.0.0 x86 Build 4748
 - Build type: qt, regular, old recompiler

**Additional context**
Attached machine [8086] Toshiba T1200:
[86Box.zip](https://github.com/86Box/86Box/files/12193218/86Box.zip)

**Comment by Fenix770** [comment]
Hello!

I tested this machine. It works on my T1200 configuration but, I'm using the internal Ricoh/JVC 20Mb HDD and Microsoft Mouse v5.0 and Compaq MS-DOS 3.30. I think that either the external XT-IDE controller is not compatible or is due to the buggy CTMouse 2.0 beta, or even the regular DOS 3.30 is not 100% compatible.

Here is the CFG and HDD image files. (I copied the games on C:\GAMES)

[Toshiba T1200 Ricoh-JVC-CFG.zip](https://github.com/86Box/86Box/files/12194359/Toshiba.T1200.Ricoh-JVC-CFG.zip)
[Toshiba T1200 Ricoh-JVC.zip](https://github.com/86Box/86Box/files/12194360/Toshiba.T1200.Ricoh-JVC.zip)

**Comment by Fenix770** [comment]
PD: I want to say that I installed Toshiba DOS 3.30 on that machine not the Compaq!

**Comment by maximus105** [comment]
Hello, I have tested your machine. On your machine with the Mouse.sys driver, these games do not freeze. If you use CuteMouse 2.0, then these games freeze from build 4438 to the latest build. Also, these games freeze on the machine [8086] Victor V86P. The bug is most likely caused by fixes for the serial port in builds 4437 and 4438, since the mouse is connected to the serial port in the 86Box machine. In build 4436 everything works fine using CuteMouse 2.0.

**Comment by OBattler** [comment]
See if this still happens now.

**Comment by OBattler** [comment]
And now the machine keeps rebooting itself.

**Comment by OBattler** [comment]
It appears to be fixed now.
