### ISSUE TITLE
HDD raw image wrong size

### ISSUE THREAD

**Issue by egrath** [86Box/86Box#3557]
**Description**

When creating a RAW HDD image in the dialogue and entering CHS values, the resulting raw image has the wrong size. For example, creating a raw image with 987 Cylinders, 16 Heads, 63 Sectors and 512 Byte/Sector should result in a file of size 509386752 bytes (987 * 16 * 63 * 512). However, the created file is of size 508559360.

**To Reproduce**
1. Add a new HDD to a emulated device
2. Set parameters to 987/16/63 and create the image in raw format
3. Calculate the expected file size and compare it to the size of the raw image created. They differ.

**Expected behavior**
Image of correct size created

**Screenshots**
![image](https://github.com/86Box/86Box/assets/1955895/fe3d0f03-3f2b-4aae-aa0d-595e1c70c64a)
![image](https://github.com/86Box/86Box/assets/1955895/3487842f-6846-45b4-9d2e-771878227fe9)
![image](https://github.com/86Box/86Box/assets/1955895/41757db2-7bd2-4df2-a01a-f89f4d7ec301)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - 86Box version: b4800
 - Build information: Old recompiler, x64

**Comment by headsetguy37** [comment]
Here's what I did to fix this:
1. Use the incorrectly sized hard disk in your machine of choice. If it automatically detects the wrong geometry (for example, 986 cylinders instead of 987), correct it.
2. Boot the emulated machine from a DOS boot disk.
3. Once the emulated machine is at the DOS prompt, run fdisk. Choose to create a primary DOS partition, use all of the available disk space and make it active.
4. Check the size of your image again.
As for why it creates a disk image of the wrong size in the first place, I can't say.

**Comment by OBattler** [comment]
NOTABUG - the size is correct, 86Box reports MiB (so divide by 1024 * 1024 = 1045876), not MB.

**Comment by lemondrops** [comment]
But the MiB/MB difference isn't even relevant here?

**Comment by lemondrops** [comment]
@OBattler I think I've tracked this down to a bug introduced in the Qt UI's reimplementation of the original Win32 image creation code: when generating a new image, the size is read directly from the "size" text box, which has only 1 MiB granularity, instead of being calculated from the CHS geometry.
