### ISSUE TITLE
[BUG]  Xi8088 and HD floppy disks

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#359]
Hello

I recently found a small issue with this machine, It does not recognize high density floppy disk in spite of the the small BIOS program allows to specify them.
I know this is BIOS  was created by a hobbyist in 2017 and included a 8-bit ISA controller that support HD and ED floppy disks.
The hd floppy drives works in PCEM. Tested with a 1.44mb and a 1.2mb.
In the other hand, in both emulators the only hard disk controller that works is IDE-XT

PD: Things unusual in this machine: 
   
- The Xi8088 board seems to be a 16-bit ISA card. 
- In PCEM/86box AT hard disk controllers can be selected.
- 1MB ram can be specified, but at startup it, counts memory up to 640kb only.

I had an old XT clone with 1mb ram and at startup the memory counter reached 1024 kb,  in spite that DOS can only use 640kb as conventional RAM.

**Comment by waltje** [comment]
Hi,

I have a real Xi8088, and I have not tested it with an 1.44M drive yet. I
will try to do that next week, but, being an XT, not sure if that will work.

> The hd floppy drives works in PCEM. Tested with a 1.44mb and
> a 1.2mb.
In an emulator, everything is possible, but that does not always mean
it is correct. See above, will try it on a real board.

> The Xi8088 board seems to be a 16-bit ISA card.
Yes. It is a 8088 machine using a 16bit ISA bus.  It is NOT an AT,
however, so AT-based boards will often fail.

> In PCEM/86box AT hard disk controllers can be selected.
This will not work with the standard BIOS, I think.  It is an XT, not
an AT.

> 1MB ram can be specified, but at startup it, counts memory up
> to 640kb only.
 Correct, it is an XT, so maximum support amount of base memory
is still 640K.  The extra 384KB will exist, but cannot be used, as it
cannot 'map' them like a 286+ can.

--Fred (waltje)

**Comment by Fenix770** [comment]
Hello 

The Xi8088 is not an original PC/XT machine. The board was created by Sergey Malinov in 2012.
At startup there is a small setup menu that can be accessed by pressing F1. There, a high density floppy drive can be specified.

The autor created an 8-bit ISA floppy controller that supports all floppys formats from 5.25 160kb to 3.5 2.88mb.

[http://www.malinov.com/Home/sergeys-projects/isa-fdc-and-uart](url)

Also, this board supports 1MB of RAM and can use parts of it as UMB memory.

This was not common feature back in the day because only a few 80286 chipsets or expensive LIM EMS 4.0 boards had the capacity to map memory in the 640kb-1024kb memory area.

Here is the link tothe board:
[http://www.malinov.com/Home/sergeys-projects/xi-8088](url)

PD: In PCEM I can use a little program called "use!umbs", it is a .sys file that can be loaded in config.sys on DOS 5.0  an later. Using the DOS=UMB statement and adding the free upper memory directions  is possible to use some memory for device drivers.

I tried to use the A000-AFFF region with CGA graphics emulation, This memory area  is used only by EGA/VGA cards, but games that use CGA graphics mode does not work. 

CheckIt 4.0 reports that these areas as "HI-RAM", also there are a lot of memory directions not used, but marked as "nothing", so I suppose these memory regions are free but there is no ram memory to map these memory regions as UMB.

**Comment by waltje** [comment]
Hi,

> The Xi8088 is not an original PC/XT machine. The board
> was created by Sergey Malinov in 2012.
Read my reply again.  I know - I have one.

> At startup there is a small setup menu that can be accessed
> by pressing F1. There, a high density floppy drive can be
> specified.
Yes, I just saw that. So, the Xi's BIOS know how to deal with
that.  DOS will not, until I believe version 5.00 or so.

> Also, this board supports 1MB of RAM and can use parts of
> it as UMB memory.
Yes, UMB will work, for some things.

> This was not common feature back in the day because only
> a few 80286 chipsets or expensive LIM EMS 4.0 boards had the
> capacity to map memory in the 640kb-1024kb memory area.
I know, I designed two of those LIM boards myself, and I wrote the
emulations for several of these cards for VARCem.

> directions not used, but marked as "nothing", so I
> suppose these memory regions are free but there is no ram
> memory to map these memory regions as UMB.
Shadowing RAM into those areas is very custom. Like you said
earlier, this was not common until the 286 came, which could
deal with that a lot better.

The 808x CPU does not allow re-mapping. Sergey added his own
memory management chip to enable or disable parts of the high
RAM area (A000-FFFF) as needed. So, you have to configure 
that chip to enable RAM at A000, for example, before you can
have that used by LUMB.

By default, all RAM between A000 and FFFF is disabled, so
enable the parts you need (A000-AFFF, D000-EFFF, maybe
a part of the F000 segment (where the main BIOS is, but does
not use all of it), and the parts of the B000 and C000 segments
that are not used.  Then, those areas will be usable by LUMB
and such.

--fred


 —
 You are receiving this because you
 commented.
 Reply to this
 email directly, view
 it on GitHub, or mute
 the thread.

**Comment by OBattler** [comment]
For what it's worth, on my end, 1.44 MB f loppies are now bootable on the Xi8088.
