### ISSUE TITLE
[BUG/WORKAROUND] Two cylinders occupied with the Adaptec AHA-1540B adapter

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#362]
I'm using the Adaptec AHA-1540B SCSI adapter emulated on the AMI486 (DataExpert OPTi-495SX based 486DX2 machine) and found that it's occupying the last two cylinders at the end of the drive instead of one.

For example, a 1 GB SCSI hard disk has 1,024 cylinders, 64 heads and 32 sectors per track. DOS and other utilities can detect up to 1,023 cylinders. The Adaptec AHA-1540B detects up to 1,022 cylinders making cylinder 1,023 inaccessible.

I've tested this with BootItNG and here's a screenshot for proof:

![20190228_122617](https://user-images.githubusercontent.com/32658796/53596390-781d7980-3b54-11e9-8cb1-fb18a8bcb81a.png)

A workaround to this issue would be to at least switch to the Adaptec AHA-1542C, use BootItNG floppy utility and then resize the partition.

Can anyone look into the issue on why the emulated Adaptec AHA-1540B adapter is occupying two cylinders at the end of the drive instead of one?

Thank you for your time. :)

**Comment by ppgrainbow** [comment]
As much as I learned. the Adaptec 1540B has the first cylinder going into the MBR and padding. The 1540B does NOT use the BIOS mailbox which is a design limitation as far as I know.

**Comment by waltje** [comment]
Most controllers of the time used the last (physical) cylinder on a drive
for maintenance and/or revectoring (bad block/track re-mapping.)

--fred

--------------------------------------------
On Thu, 2/28/19, ppgrainbow <notifications@github.com> wrote:

 Subject: [86Box/86Box] [BUG/WORKAROUND] Two cylinders occupied with the Adaptec AHA-1540B adapter (#362)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Date: Thursday, February 28, 2019, 3:32 PM
 
 I'm using the Adaptec
 AHA-1540B SCSI adapter emulated on the AMI486 (DataExpert
 OPTi-495SX based 486DX2 machine) and found that it's
 occupying the last two cylinders at the end of the drive
 instead of one.
 For example, a 1 GB SCSI hard disk has 1,024 cylinders,
 64 heads and 32 sectors per track. DOS and other utilities
 can detect up to 1,023 cylinders. The Adaptec AHA-1540B
 detects up to 1,022 cylinders making cylinder 1,023
 inaccessible.
 I've tested this with BootItNG and here's a
 screenshot for proof:
 
 
 A workaround to this issue would be to at least switch to
 the Adaptec AHA-1540C, use BootItNG floppy utility and then
 resize the partition.
 Can anyone look into the issue on why the emulated
 Adaptec AHA-1540B adapter is occupying two cylinders at the
 end of the drive instead of one?
 Thank you for your time. :)
 
 —
 You are receiving this because you are subscribed to this
 thread.
 Reply to this email directly, view it on
 GitHub, or mute
 the thread.

**Comment by ppgrainbow** [comment]
I found it quite odd for the AHA-1540B controller to use the last physical cylinder for maintenance and/or re-vectoring.

Since a 1 GB SCSI hard disk has 1,023 cylinders and if the data gets stored there, would I end up risking possible data corruption or data loss on the 1,023rd cylinder?

**Comment by waltje** [comment]
On an emulator, which doesnt do revectoring, no.

--fred

--------------------------------------------
On Thu, 2/28/19, ppgrainbow <notifications@github.com> wrote:

 Subject: Re: [86Box/86Box] [BUG/WORKAROUND] Two cylinders occupied with the Adaptec AHA-1540B adapter (#362)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Fred N. van Kempen" <decwiz@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Thursday, February 28, 2019, 7:05 PM
 
 I found it quite odd
 for the AHA-1540B controller to use the last physical
 cylinder for maintenance and/or re-vectoring.
 Since a 1 GB SCSI hard disk has 1,023 cylinders and if
 the data gets stored there, would I end up risking possible
 data corruption or data loss on the 1,023rd cylinder?
 
 —
 You are receiving this because you
 commented.
 Reply to this
 email directly, view
 it on GitHub, or mute
 the thread.

**Comment by ppgrainbow** [comment]
Good to hear that.

If this is a design limitation of the Adaptec AHA-1540B controller, would it be possible to mark this as WONTFIX?
