### ISSUE TITLE
IRQ 2 Issue on AT without Pending IRQ on PIC 2

### ISSUE THREAD

**Issue by AITUS95** [86Box/86Box#3650]
I get the following message when i try to install blood 2 on my machine, the PIC mode is set to "slow".

**Screenshots**

![PIC](https://github.com/86Box/86Box/assets/48457684/67fee8b1-1008-4b55-a776-a3a9ca2736c6)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - 86Box version: v4.0 build 5000
 - Build information: ODR

**Additional context**

I attach my virtual machine for further testing: [VM](https://drive.google.com/file/d/10WDxGd-vclL-_C3vc8Y-k5zWz2_vsdoG/view?usp=sharing)

**Comment by Tritonio** [comment]
Copy-pasting my message from Discord:

I've encountered this error popup and crash twice with 86Box 4.0. On Win95 and Win98, I think in both cases it happened while copying files from a mounted folder as CDROM to one of the Guest HDDs. I'm emulating A-Trend ATC-1415 with AMD Am486DX4@100MHz. Has happened both with and without Dynamic Recompiler. 16MB RAM. Network device is 3Com Etherlink II. Standards BIOS settings. Storage devices are configured to run at high speeds. IRQ2 seems to be (according to Win95 device manager) assigned to Programmable Interupt Controller.

Is that an error of 86Box or does it simply mean that the guest did something that would have probably crashed the real machine too?

**Comment by AITUS95** [comment]
issue fixed with build 5007

**Comment by AITUS95** [comment]
I reopen the commit, the error still seems to be present in the latest version of 86box...
![pic](https://github.com/86Box/86Box/assets/48457684/741c038e-4f16-481d-b1f5-7f9bbae5d3b1)

**Comment by AtlasHackert** [comment]
Sorry for the simple +1, but I'm experiencing this too on build 5000. I'm trying in a Windows 95 box to install a program (NSIS-installer) from a self-made ISO mounted to a CD-ROM drive, but at random points during extracting I get total hangs, crash-to-desktops (86Box just disappears), or this error message.

**Comment by spr93** [comment]
I've been getting this regularly on OS/2 3 and 4.x VMs, both Pentium and Pentium II configurations.  Both Slot 2 and i1440x configurations. 

It's happening to me even when there's no disk I/O and no CD mounted.  I got a couple VMs to stop doing this by disabling all APM features (both in the BIOS and the OS), but that may just be coincidence because I just this problem in a VM that had all APM disabled.

In fact, the configuration that just crashed may be helpful because it's not very exotic:
- i440GX 
- BIOS:  Disabled APM; disabled SCSI; disabled USB.  Non-PnP OS; manual configuration.
- Hard drives:  1 IDE hard disk (IDE 0:0)
- Other storage:  2 floppies (1x1.44MB, 1x2.88), one ATAPI CD-ROM (0:1) - none were active, none in use
- PS/2 mouse **this is common to all configurations that have crashed**
- Network AMD PCnet PCI **this is common to all configurations that have crashed, but there has not been network traffic when crashes occur ***
- S3 PCI graphics
- One serial port; not active.  No other ports.
- No other devices
- Dynamic recompiler
- Hard float **this is common to all configurations that have crashed**
- Time sync enabled, local time **this is common to all configurations that have crashed**

**Comment by cold-brewed** [comment]
@spr93 Would you be able to zip up the os/2 4.x machine directory (config, nvr, disk) and share somewhere so we can try and reproduce?

**Comment by AITUS95** [comment]
Resolved in build #5027, @OBattler  thanks again!

**Comment by AtlasHackert** [comment]
Seems fixed for me too! Thank you all!
