### ISSUE TITLE
[Feature Request] Acer V30 Motherboard Support

### ISSUE THREAD

**Issue by headsetguy37** [86Box/86Box#367]
I have a Compudyne from 1995, during its last days when they were manufactured by Acer. It uses an Acer V30 motherboard. I also have Acer restore media that works with the V30 (it doesn't detect the V35n or M3a as compatible Acer machines), but I don't want to try and use the restore media on my Compudyne yet. It was the first computer I ever used, and it means a lot to me as a result. I don't have any spare hard drives; I'd love to be able to emulate it in 86Box.
I can take some pictures of the motherboard if you need them; there's no substantial difference between a V30 used in a Compudyne vs. a V30 used in an AcerAcros or AcerEntra from the same time period, other than the BIOS (no Acer logo--or any logo, for that matter--on the Compudyne version). I can also provide the latest ROM file I could find, which is Acer-branded, as far as I'm aware.

-Johnny

**Comment by headsetguy37** [comment]
Okay, confession time: I've been trying to add the V30 myself since requesting this. The key word being "trying"; when I try and boot from it, I get several errors, it doesn't let me enter the BIOS settings with an emulated Ctrl_Alt_Esc, and pressing F1 to resume gets me the infamous "Password Violated, System Halted!" error. I've been researching this and found out the same thing happened when M3a and V35n support were in development; how did that get resolved?
If it helps, the board for sure uses the SMC FDC37C665GT and Intel 430FX. Also, I think the V30 BIOS doesn't have an Acer logo no matter what.

**Comment by headsetguy37** [comment]
I apologize for the frequent comments on this issue. I am stumped. Should I provide a link to the BIOS file I used?

**Comment by waltje** [comment]
That would probably help.

To add a new machine, you need to:

- have the system's BIOS images,
- add a system ID entry to rom.h (or machine.h, cant remember),
- add code to load the BIOS to rom.c,
- add a line to machines/machine_table.c with the machine's specs and init function,
- implement that init function in machine/m_something.c,
- and make sure all hardware on that board is implemented in the code.

That said, it all starts with having the BIOS code, and having that loaded properly.

--fred

--------------------------------------------
On Wed, 3/27/19, headsetguy37 <notifications@github.com> wrote:

 Subject: Re: [86Box/86Box] [Feature Request] Acer V30 Motherboard Support (#367)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Date: Wednesday, March 27, 2019, 10:30 AM
 
 I apologize for the frequent
 comments on this issue. I am stumped. Should I provide a
 link to the BIOS file I used?
 
 —
 You are receiving this because you are subscribed to this
 thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by headsetguy37** [comment]
It's the last step (implementing the hardware) that's stumping me.

Link to the BIOS ROM file: https://www.dropbox.com/s/ommg0ybcxis94mk/V30R01N9.BIN?dl=0

Some pictures of motherboard components: https://www.dropbox.com/s/nu2etrqqlwtyopx/V30-MB-PICS.zip?dl=0

**Comment by waltje** [comment]
Hrrm.  Dropbox wont let me download.

Could email them to me at decwiz@yahoo.com so I can have a look?

--fred


__
Sent from my Samsung Note4 LTE smartphone


-------- Original message --------

**Comment by TC1995** [comment]
I will test this now, since you said that it features a 665gt and 430fx.

**Comment by OBattler** [comment]
Yes, both of them are already emulated, so it theoretically should be doable.

**Comment by headsetguy37** [comment]
New info: the board uses an Acer 90M002A for the keyboard controller.

**Comment by waltje** [comment]
I alrready told them, Johnny, and committed my changes so far.

--fred

--------------------------------------------
On Tue, 4/30/19, headsetguy37 <notifications@github.com> wrote:

 Subject: Re: [86Box/86Box] [Feature Request] Acer V30 Motherboard Support (#367)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Fred N. van Kempen" <decwiz@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Tuesday, April 30, 2019, 7:40 AM
 
 New info: the board uses an Acer
 90M002A for the keyboard controller.
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by headsetguy37** [comment]
Thanks.

**Comment by headsetguy37** [comment]
I noticed a fair number of other machines have been added lately; is there any progress on the V30?

**Comment by OBattler** [comment]
None, whatsoever, unfortunately.

**Comment by tiseno100** [comment]
Just noticed it. I might check it. The Acer machines we emulate have two additional ports 0xEA & 0xEB. The lack of them triggers the "Password Violated. System halted." message. I don't know if V30 has the same ones.

**Comment by OBattler** [comment]
This now closed because the machine has been added and works.
