### ISSUE TITLE
Midtown Madness 1 immediate hard crashes when you select any event on PII hardware

### ISSUE THREAD

**Issue by KoghaandSooga** [86Box/86Box#3710]
**Describe the bug**
Upon clicking Quick Race the game will immediately cause 86box to hard lock and close out. The other modes do not do that. This does NOT occur at all on PCEM.  On Single Race you can get as far as the vehicle selection screen briefly hearing the loud police siren before it hard locks 86box and crashes it out with no error message.

**To Reproduce**
1. Run Midtown Madness
2. Select any of the modes

**Expected behavior**
To be able to select different race types.

**Screenshots**
If applicable, add screenshots
![Monitor_1_20230929-102202-350](https://github.com/86Box/86Box/assets/109556152/8425218f-89d7-4fda-bb14-3a832916befc)
![Monitor_1_20230929-102221-974](https://github.com/86Box/86Box/assets/109556152/7f43a5e0-38bd-46a6-bc73-2d34abc7447e)
 to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 pro:
 - 86Box version 4.0 official release build.
 - Build information: [i.e. new/old dynarec, architecture and build type]

**Additional context**
For some reason the Quick Race crashes 86box immediately where as Single Race you can get as far as briefly hearing the police siren on the vehicle select before it cuts off and crashes 86box hard.

Note: This error DOES NOT occur on PCEM which is rather odd considering both do PII hardware and I didn't have any stuttering here yet on PCEM I cannot emulate PII at all so I had to go down to Pentium MMX OverDrive to play this game properly.  I guess I'll stick to there as I got my Switch Pro Controller to work as a SideWinder Pad.

**Comment by OBattler** [comment]
Which Pentium II did you choose on 86Box? Klamath or Deschutes?

**Comment by KoghaandSooga** [comment]
First I did Celeron (COington) then did Deschutes.  I tried various different boards of the same slot 1 so maybe it wasn't the slot but rather the CPU?

**Comment by KoghaandSooga** [comment]
> Which Pentium II did you choose on 86Box? Klamath or Deschutes?

I meant to reply to you. Whoops!

**Comment by pankoza2-pl** [comment]
are you using a 32-bit or 64-bit version of 86Box?
the 64-bit version is currently buggy

**Comment by OBattler** [comment]
Yes, the 64-bit version of 86Box currently has some bugs (including a severe bug with regards to the 64-bit Voodoo dynamic recompiler that we still do not understand what causes it) and is also slightly slower than the 32-bit version.

**Comment by KoghaandSooga** [comment]
Sadly I coul

> Yes, the 64-bit version of 86Box currently has some bugs (including a severe bug with regards to the 64-bit Voodoo dynamic recompiler that we still do not understand what causes it) and is also slightly slower than the 32-bit version.

32 bit version doesn't even work! Sadly I couldn't try it. 64 bit at least Windows 98 installed despite those glitches.

**Comment by OBattler** [comment]
The 32-bit version does work, I use it all the time.

**Comment by OBattler** [comment]
Also, calling 86Box experimental just because it has one bug that you don't like, is itself rude.

But anyway, issue closed since clearly the person reporting it has no intention to give further feedback.

**Comment by OBattler** [comment]
It appears this can be closed as fixed since TC1995 has now verified that he can no longer reproduce this bug.

**Comment by KoghaandSooga** [comment]
All I know is half the time on both versions the 'window' where the emulator is will often not open up while you hear the sound and I thought it might have been related to the motherboard I was emulating so I played around with them but they produced the same results though not at the same time.  I KNOW 86box wasn't originally like this.

**Comment by OBattler** [comment]
I'm not a child (I'm in fact 36, almost 37).

Also, where exactly have I been mean or salty? You said you were going to stick to PCem, so I assumed based on that that you were not going to give further feedback here. My assumption could well have been wrong, and in that case, I apologize.

You said the 32-bit version doesn't work at all, so I need to at least know what build of 86Box you were running, and if it still occurs on the latest build.

And I would appreciate it if you could also test to see if the problem still occurs on the 64-bit version as well.

> the lack of a physical CD drive

That is actually in the process of being re-added, it's just going to take a while due to the structural differences between the two emulators.

And to address one last thing:

> Again this crash does NOT occur on PCEM which you'd think the behavior would be the same on both? If it doesn't crash on PCEM it shouldn't crash on this or if it crashes on this it should crash on PCEM.

Not necessarily. The two emulators have diverged significantly already and, for example, the P6 emulation has been added separately on both (PCem in fact added it after us), and use different timings code from it. Both have their imperfections - I have an import somewhere of PCem's P6 timings code to 86Box and it hard freezes the emulator when attempting to boot Windows XP on the ASUS P2B-LS (a machine PCem does not emulate). 86Box's code appears to not freeze there but it at least used to freeze in your game, according to your report. TC1995 tried to reproduce it on the latest build of 86Box and could not reproduce it, hence my request for you to retest it on the latest build of 86Box.

**Comment by oshogun** [comment]
I could also reproduce the same issue (or similar issue) here.  Running build 6130 with this machine:
![image](https://github.com/user-attachments/assets/9b3f39ae-57e2-4f16-a78a-509731d44e77)

Also worth pointing out that this game in particular is ridiculously tricky to run even in real hardware. I remember it being very picky with which machines I could actually get it running at all, and crashes were commonplace in all the win 98 machines I had.
