### ISSUE TITLE
[Feature Request] HP Vectra emulation, HIL support, etc.

### ISSUE THREAD

**Issue by Spagheta-DSi** [86Box/86Box#377]
I would like to see stuff like HIL bus emulation, EISA, Vectra emulation, and Gateway PC (e.g. 4DX2) emulation in the future.
Sadly, I couldn't find the BIOS file for the Gateway 2000 4DX2.

If you want the BIOS file itself, DM me on Discord at: Sauce#4632.
Thanks!
~Sauce

**Comment by waltje** [comment]
I do have the HIL specs etc, so it's doable.  

--fred

--------------------------------------------
On Thu, 4/18/19, Swag I. Swag <notifications@github.com> wrote:

 Subject: [86Box/86Box] [Feature Request] HP Vectra emulation, HIL support, etc. (#377)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Date: Thursday, April 18, 2019, 12:50 PM
 
 I would like to see stuff like
 HIL bus emulation, EISA, Vectra emulation, and Gateway PC
 (e.g. 4DX2) emulation in the future.
 
 Sadly, I couldn't find the BIOS file for the Gateway
 2000 4DX2.
 If you want the BIOS file itself, DM me on Discord at:
 Sauce#4632.
 
 Thanks!
 
 ~Sauce
 
 —
 You are receiving this because you are subscribed to this
 thread.
 Reply to this email directly, view it on
 GitHub, or mute
 the thread.

**Comment by SauceMercuryNetworks** [comment]
Nice.

**Comment by SauceMercuryNetworks** [comment]
And it has a motherboard chipset made by VLSI Technologies, not sure what model it is. :stuck_out_tongue:

**Comment by OBattler** [comment]
Closing this - I have noted it down and will put all of your requests inside one single pin the Discord server.
