### ISSUE TITLE
FMVs in Sierra games will lag if Dynamic Recompiler is turned on

### ISSUE THREAD

**Issue by ualaa1** [86Box/86Box#3820]
### What happened?

Games I have tested so far:
Torin's Passage
Phantasmagoria

At both 33 mhz and 66mhz speed modes. With Dynamic Recompiler turned on, the FMVs in both games lag heavily while the main gameplay generally runs well. This is in the DOS versions and not the Windows versions.
With Dyamic Reompiler turned off FMVs seems to run fine

### Configuration file

```ini
[Config.zip](https://github.com/86Box/86Box/files/13324735/Config.zip)
This config is with the Dynamic Compiler disabled
To reproduce the issue, enable the compiler
```

### Operating system

Windows 10

### CPU

Intel Core i7-9750H 

### 86Box version

v4.0

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by ualaa1** [comment]
Some more updates:
Inherit the Earth (with Microsoft sound for speech as 86-Box appears to not emulate soundblaster speech correctly for the game)
and Star Trek Pinball has gameplay playing normally but music lagging heavily in-game with Dynamic Recompiler turned on

**Comment by eddmanx** [comment]
I tested your config with build 5434 and videos play just fine with dynarec enabled.

**Comment by OBattler** [comment]
Perhaps this is just more instance of the known lag in new recompiler vs. old recompiler (see eg. Mapedit 8.4 and Sound Blaster WaveSynth), in which case, it's a CANTFIX, really, at least until a better recompiler is written.

**Comment by OBattler** [comment]
OK, so this turns out to be unrelated to said known lag. Now, you're:
1. Emulating a S3 ViRGE which are known to currently have sub-par performance;
2. Doing this all on a laptop CPU, I hope at least with host Windows power settings set to high performance.

All in all, a suboptimal situation. Since this is a DOS game, you should be able to switch to something better performing such as S3 Trio64 or S3 Vision 968 and therefore, mitigate #1.
