### ISSUE TITLE
Cannot configure more than 128MB RAM

### ISSUE THREAD

**Issue by 12skinned75** [86Box/86Box#384]
If you try to make a machine with more than 128MB RAM, it will just set the RAM to 128MB. This is very problematic when trying to make virtual machines for gaming or Windows XP or Longhorn.

**Comment by 12skinned75** [comment]
Im using the 86box-optimized Core2 version, build 1841.

**Comment by daviunic** [comment]
This is likely a limitation of the board you're using.

**Comment by waltje** [comment]
It is.
--------------------------------------------
On Thu, 5/16/19, David Simunič <notifications@github.com> wrote:

 Subject: Re: [86Box/86Box] Cannot configure more than 128MB RAM (#384)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Date: Thursday, May 16, 2019, 2:34 AM
 
 This is likely a
 limitation of the board you're using.
 
 —
 You are
 receiving this because you are subscribed to this thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by ppgrainbow** [comment]
What emulated machine or motherboard are you using?

If you don't know the exact name of the motherboard, we won't know.

**Comment by dhrdlicka** [comment]
For Windows XP and later, you will probably want to use a hypervisor such as VirtualBox or VMware. Regular builds of 86Box emulate a Pentium at most, which is the very minimum that XP requires.

**Comment by 12skinned75** [comment]
It was the jetway board.

**Comment by msdosmanfred** [comment]
For more than 128 MB RAM you need to set up a Socket 7 HX motherboard, the other ones doesn't support more than 128 megs.
