### ISSUE TITLE
AMD CPU's not showing up on Socket 7 motherboards

### ISSUE THREAD

**Issue by SirScotty1** [86Box/86Box#393]
For some reason, AMD CPU's are no longer showing up under any of the Socket 7 motherboards.   The same boards under PCem 15 show the AMD CPU's no problem.  86Box is only showing Intel, Cyrix and IDT.

**Comment by ppgrainbow** [comment]
Are you using the latest stable or developer build of 86Box? That's what I want to know.

**Comment by OBattler** [comment]
1. 86Box does show the AMD CPU's, on the Dev builds only, and the list is a bit different from PCem's, but the emulation is incomplete;
2. 86Box still has the old dynamic recompiler (and will have it as main until after v2.00 is out, until after the new one stabilizes and improves in the first place, as it goes down to 4% in situations when the old one ran at solid 100%).

**Comment by waltje** [comment]
As far as I know, both 86Box and VARCem have the AMD chips in the 'in development" mode,
because they are not working properly.  Neither do the PCem ones, but they don't seem to care.

So, retry using the 'dev build' of the emulator, that should have them- mine does.

--fred

--------------------------------------------
On Sun, 6/9/19, SirScotty1 <notifications@github.com> wrote:

 Subject: [86Box/86Box] AMD CPU's not showing up on Socket 7 motherboards (#393)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Date: Sunday, June 9, 2019, 6:27 AM
 
 For some reason, AMD CPU's
 are no longer showing up under any of the Socket 7
 motherboards.   The same boards under PCem 15 show the AMD
 CPU's no problem.  86Box is only showing Intel, Cyrix
 and IDT.
 
 —
 You are receiving this because you are subscribed to this
 thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
