### ISSUE TITLE
Realtek RTG 3106 VGA bugs

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#3996]
### What happened?

I tested Realtek RTG 3106 VGA. It works fine under Windows 3.0 and 3.1. However I found bugs:

1. The test utility (VTEST) included on the VGA driver disk shows corrupted graphics on the last 2 or 3 screens.
2. The VBETEST utility included on Sitech Display Doctor throws a protection error.
3. The UNICENTR program shows a duplicated screen at 512x384 256 color mode. (this mode is added by the VBE 2.0 standard and I'm not sure if it is a software or hardware bug)
4. The remaining modes looks right but I could not mode the screen (with the keyboard arrows) to adjust the video mode.

PD: I installed the Sitech Display Doctor to test the Neopaint DOS app. Neopaint uses a generic VESA driver on the Realtek that reboots the machine when a SVGA video mode is selected, However the Universal VESA driver included in the Sitech software fixes this issue.

The test utility is in C:\VGAUTIL folder. The C:\VGAUTIL2 folder includes about the same test utility, the only difference is one was installed from 3105 floppy disks and the other from 3106 floppy, but seem to be the same version of the utility.

Screenshots:

UNIVBE error:
![Monitor_1_20240105-105425-537](https://github.com/86Box/86Box/assets/31600563/3a07bc96-6fcd-4b33-9dda-04d35ed20b02)

Test utility error:
![Monitor_1_20240105-105541-983](https://github.com/86Box/86Box/assets/31600563/7ca4efd0-6af1-4aeb-a5fb-5ea6113d1fa3)
![Monitor_1_20240105-105547-353](https://github.com/86Box/86Box/assets/31600563/a30dff4b-69ce-4db0-a333-7351a6342b5d)
![Monitor_1_20240105-105552-181](https://github.com/86Box/86Box/assets/31600563/8430df6a-9621-40a5-b33e-e8d7908c17cf)

Also the 40x25 text mode seems to be out of sync since the "T" for text cannot be seen.
![Monitor_1_20240105-105602-871](https://github.com/86Box/86Box/assets/31600563/c411ac54-b23a-4a94-aec9-4a8218b60dc8)

The 512x384 256 color mode test:
![Monitor_1_20240105-110352-631](https://github.com/86Box/86Box/assets/31600563/7023ac50-58b5-4d16-a0b7-79a574a50229)

Files:

HDD:
[386 DX +Realteck VGA.zip](https://github.com/86Box/86Box/files/13842979/386.DX.%2BRealteck.VGA.zip)

NVR:
[nvr.zip](https://github.com/86Box/86Box/files/13842984/nvr.zip)

### Configuration file

```ini
[Realtek RTG3106 (ISA)]
memory = 1024

[General]
vid_renderer = qt_software
vid_resize = 1
enable_overscan = 1
rctrl_is_lalt = 1

[Machine]
machine = ami495
cpu_family = i386dx
cpu_speed = 25000000
cpu_multi = 1
cpu_use_dynarec = 0
fpu_softfloat = 0
time_sync = local
mem_size = 4096

[Video]
gfxcard = rtg3106

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sbprov1
fm_driver = nuked

[Network]
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 31, 16, 967, 0, ide
hdd_01_fn = 
hdd_01_speed = ramdisk
hdd_01_vhd_blocksize = 1024
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
fdd_02_type = 525_2hd
```

### Operating system

Windows 10 22H2

### CPU

i5 4210U

### 86Box version

4.1.0.5344

### Build architecture

Windows - x86 (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
This is weird, 320x200x256 works properly when a game/utility uses such mode, for example.

**Comment by iamgreaser** [comment]
Does anyone have one of these cards? Because it seems we'd be much more likely to get our hands on a card (heck, even get someone to put one into a computer and actually use it!) than we would be to get an actual datasheet from a website that isn't some account-walled thing which is likely a lie, or a link to alldatasheet which does NOT have any of the relevant datasheets on it.

The reason being that it seems that the display enable skew amount needs to be set differently from what some other SVGA chipsets are expecting - the S3 Trio64V2/DX always uses a skew of 0 (unless you want to hide columns on the left and show the same number of columns on the right), but an EGA tends to use a skew of 1 except for the 64KB 640x350 modes where it uses a skew of 0. Having a datasheet may actually help here. But that's a number we need to play around with on a real card.

As for why you can't move the screen around... I hate to break it to you, but the overscan in 86Box is currently fake. It exists purely to show the border colour.

**Comment by OBattler** [comment]
The protection error is normal - enable the FPU.

And the 40x25 was broken on all the cards, so it should be fixed now.

**Comment by OBattler** [comment]
Closing this as CANTFIX until a proper datasheet of the Realtek is found.
