### ISSUE TITLE
86box running porly

### ISSUE THREAD

**Issue by Thewolfguy** [86Box/86Box#4210]
### What happened?

i have a intel core i7 10750 and 8gb ram and a nvidia geforce 2060
but i have problems running a intel petiums whit 200 hz whit only 50 % - 68 % speed

### Configuration file

```ini
t
```

### Operating system

windows 11

### CPU

intel core i7 10750

### 86Box version

newst

### Build architecture

Windows - x64 (64-bit)

### Build type

- [X] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by TC1995** [comment]
Most likely your host is not powerful enough to handle such speeds.

**Comment by webfischi** [comment]
I don't know, what kind of emulation 86box is using, but if your host is misconfigured you'll experience heavy slow downs in other VMs like VirtualBox as well. I would set up a VirtualBox VM first, because it shows a turtle in the bottom bar if the system is not set upcorrectly and a V if it's running at full speed. Something like that would be a great addition for 86box, too.

There should only be a performance drop on Windows start up. I set up a Pentium II 300 MHz with Voodoo 3 3000 and 256 MB RAM. My System is an i7 12700k, GeForce 3060Ti and 32GB RAM at 3600MHz, OS Windows 11 23H2 and 86Box 4.1

**Comment by TC1995** [comment]
86Box is doing pure emulation, not virtualization.

**Comment by cold-brewed** [comment]
Please provide the configuration file. We can't do much without it.

**Comment by webfischi** [comment]
> 86Box is doing pure emulation, not virtualization.

Good to know, then it's not powerful enough, if the Windows power settings are not set to max performance of course, because the i7 10750 is a mobile CPU. Standard setting is energy saving, which is like driving a car without releasing the handbreak.

**Comment by OBattler** [comment]
Closing this because it's NOTABUG - configure your Windows power settings properly.
