### ISSUE TITLE
Everex EV-159 RAM 3000 Deluxe Expanded Memory board not working from 1871 onwards 

### ISSUE THREAD

**Issue by Mal752** [86Box/86Box#435]
Summary : 

Issue : Everex EV-159 expanded memory board not working

**Problem** detected in release : **1871 onwards and upto the latest 1894**

Last working in : release 1870

Configuration : Award 286 machine with 2MB RAM with Everex 159 w/ 1MB EMS. (Configuration checked and enabled and address range unaltered as in working releases.)

Symptom : When loading the driver in config.sys : message says no expanded memory available

Everex driver version in config.sys : 4.01

                 ******************************

I like using the "Expanded Memory Boards" in the Award 286 and the one that works for me best is the Everex EV-159 RAM 3000 Deluxe 'board". I'm using the official driver downloaded from the net. 

Due to the current mouse-crash in fullscreen (429) issue, I have been stuck to 1843 which so far works best for my needs.

Issue : Everex EV-159 does not work with newer revisions, and I have narrowed down the culprit to  the release no. 1871. I have made sure the configuration for this "board" is the same with my previous release settings.

The latest and last version that works is release 1870.

Thank you.

**Comment by OBattler** [comment]
Could you upload your hard disk image, 86box.cfg, and NVR folder please, so I can reproduce this bug?

**Comment by Mal752** [comment]
Hi, here's the link to download : 

https://drive.google.com/open?id=1kHtUSjaoBplj6HCi46HZrmvtOlnArk7M

Thanks.

**Comment by MyTDT-Mysoft** [comment]
so you have success configuring it... would it only work on 286? or i would be able to get it working on a 386/486 system as well? i tried... to setup this card with this configuration... and the machine setup to 8mb
![image](https://github.com/86Box/86Box/assets/16870416/1b347f5d-5715-47ae-8f13-e00bb1ecb07a)
and configured it with the drivers like this:
![image](https://github.com/86Box/86Box/assets/16870416/4c1b47b8-1f7d-4447-b82f-944ecd593ed8)
altough i guess most of those configurations is in helping changing the switches... 
as the command line to be added to the .sys does not account for start address or anything

but when "testing" on that program i always get bad banks... and the .sys when loaded always says..
![image](https://github.com/86Box/86Box/assets/16870416/00b1262d-7436-47ec-b5ae-145795473527)

so did i did something wrong?

so yeah this only work with 286? (i'm just trying to have some EMS working without changing the processor to V86 :P)

**Comment by Fenix770** [comment]
The start address is here the extended memory of the main board ends and the memory filling of the board starts. 
Works on my end! You should specify the continuous size (the amount fo extended memory to be added).

The EMS memory is = to total RAM - Continuos RAM size.

![Everex RAM deluxe](https://github.com/86Box/86Box/assets/31600563/dcb4364f-d7b5-40ab-9719-accbdf4557c6)



![Monitor_1_20240126-185330-551](https://github.com/86Box/86Box/assets/31600563/79ca11bd-0d3a-451f-83f7-0528888e8ae7)

**Comment by Fenix770** [comment]
PD: Each board supports up to 3mb of extended and to 2mb of EMS on 86Box because is the maximum each port can handle. On real hardware 3mb of EMS is possible because it can handle a second port if the EMS RAM is more that 2mb.

**Comment by MyTDT-Mysoft** [comment]
ok... yeah it works on 286,386... some 486... but not all it start failing to detect... not sure exactly what makes it fail... but it's just speed (because it worked with a 484, dx4-100, but only with some chipsets... i will try then to see if i can find a PCI one where that works...)

**Comment by Fenix770** [comment]
I used the Hyundai 286C at 12 Mhz. Anyway it is not required on 386+ because you can use EMM386 or other 386 memory manager. 
I doubt it will work on real 386 DX or latter because the 32-bit memory and clock of the RAM bus used in these machines. The Everex RAM Deluxe 3000, works in 16-bit mode only on 286/8. The 286/10 requires 110/100 ns RAM chips, (higher CPU clocks required faster RAM) but the card do not suppot it, so in that case the 8-bit bus mode have to be used.

**Comment by MyTDT-Mysoft** [comment]
yeah, if they must be setup like that to be able to extend ram... well... but if i get something working on 86box it will be good enough (trying to have all in 1..... PCI (3dfx) + EMS + UMB... (also wont use EMM386 because it switches to v86 mode)... but yeah it's fine i dont get EMS... i can use "ems magic" to have EMS over XMS... but that's slower because of the copy...

**Comment by MyTDT-Mysoft** [comment]
ok i probabily need to enable the 15mb memory hole and use 16mb of ram... for it to work with PCI... not use if i need umbpci to enable the umb's so that they can be used  by the driver... or if i must enable that before the UMB... so that umb does not get used by umb pci... still couldnt get a combination that actually works... but i'm trying :)
