### ISSUE TITLE
Can't get freedos/dos7 FDISK to recognize disk

### ISSUE THREAD

**Issue by Thraka** [86Box/86Box#4426]
### What happened?

When booting off the attached floppy (I also tried freedos 1.2 and freedos 1.3, same results) the FDISK command says NO FIXED DISKS FOUND. If I attach the hard drive image and floppy to the MiSTer AO486 the disk is found fine via FDISK. I've tried a different UMC motherboard and it too has huge problems creating/managing disks. I tried FDISK on an SIS 486 motherboard and it worked fine.

### Configuration file

```ini
[General]
vid_renderer = qt_software
video_fullscreen_first = 0
confirm_exit = 0
video_filter_method = 0
video_fullscreen_scale = 3

[Machine]
machine = m919
cpu_family = idx4
cpu_speed = 100000000
cpu_multi = 3
cpu_use_dynarec = 1
time_sync = local
fpu_softfloat = 0
fpu_type = internal
mem_size = 16384

[Video]
gfxcard = mach8_vga_isa

[Input devices]
mouse_type = msserial

[Sound]
sndcard = sbprov1
fm_driver = nuked
midi_device = fluidsynth

[Network]
net_01_card = ne2k
net_01_net_type = slirp
net_01_link = 0
net_02_link = 0
net_03_link = 0
net_04_link = 0

[Storage controllers]
hdc = internal
cassette_mode = load

[Hard disks]
hdd_01_parameters = 17, 5, 855, 0, ide
hdd_01_fn = C:/temp/hds/new_base_6.img
hdd_01_speed = 1992_3600rpm
hdd_01_ide_channel = 0:0

[Floppy and CD-ROM drives]
fdd_01_type = 35_2hd
cdrom_01_parameters = 1, atapi
cdrom_01_ide_channel = 1:0
fdd_01_fn = D:/Emulated Systems/86box/Floppy/DOS7 Ultimate Boot.img
cdrom_01_type = 86BOX_CD-ROM_1.00

[3Com EtherLink (3c500/3c501) #1]
mac = 01:d6:51

[3Dfx Voodoo Graphics]
type = 0
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dithersub = 1
dacfilter = 0
render_threads = 2
sli = 0
recompiler = 1

[Novell NE2000 #1]
base = 0300
irq = 3
bios_addr = 00000
mac = 3c:d2:bd

[Sound Blaster Pro v1]
base = 0220
irq = 5
dma = 1
opl = 1
receive_input = 1

[FluidSynth]
sound_font = C:/temp/soundfont/Roland SC-55 v3.7.sf2
output_gain = 100
chorus = 1
chorus_voices = 3
chorus_level = 20
chorus_speed = 30
chorus_depth = 80
chorus_waveform = 0
reverb = 1
reverb_room_size = 20
reverb_damping = 0
reverb_width = 5
reverb_level = 90
interpolation = 2

[NE2000 Compatible #1]
mac = 62:86:de
```

### Operating system

Windows 11

### CPU

i9-12900H

### 86Box version

v4.1.1

### Build architecture

Linux - ARM (32-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

### Additional context

[Floppy and HD Image](https://github.com/86Box/86Box/files/15228783/files.zip)

**Comment by saipan7** [comment]
the m919 machine have the freedos fdisk bug since 86Box 3.11 (https://github.com/86Box/86Box/releases/tag/v3.11)  
![freedos 1.3 fdisk err build 4311](https://github.com/86Box/86Box/assets/127716019/a5f0c058-6e77-4cb5-aa16-a8a60a5abded)

the freedos fdisk bug still exist upto the latest beta/jenkins build https://ci.86box.net/job/86Box/5740
![freedos 1.3 fdisk err build 5740](https://github.com/86Box/86Box/assets/127716019/f3db9580-2368-40dc-9976-e668ebe5e8ab)

if you must to use umc machine, try use ecs486 machine. the machine don't have the freedos fdisk bug.

Freedos 1.3 fdisk ok build 4311
![freedos 1 3 fdisk ok build 4311 on umc ecs486](https://github.com/86Box/86Box/assets/127716019/f63c90c4-6719-4009-a120-1887edd95868)

Freedos 1.3 fdisk ok build 5634
![freedos 1 3 fdisk ok build 5634 on umc ecs486](https://github.com/86Box/86Box/assets/127716019/21e704f1-f3bb-427b-9a19-34f484b5f643)

Freedos 1.3 fdisk ok build 5740
![freedos 1 3 fdisk ok build 5740 on umc ecs486](https://github.com/86Box/86Box/assets/127716019/b904ef17-4299-4ec3-84bc-ffedd033a823)

Freedos 1.3 install fdisk & format test ok on build 5634
![freedos 1 3 install step 1 ok build 5634 on ecs486](https://github.com/86Box/86Box/assets/127716019/3ea9517d-8159-4984-848e-78a50c13ec2b)

![freedos 1 3 install step 2 ok build 5634 on ecs486](https://github.com/86Box/86Box/assets/127716019/d419f66d-2983-447c-8f00-63f828a5dbb5)

![freedos 1 3 install step 3 ok build 5634 on ecs486](https://github.com/86Box/86Box/assets/127716019/d33c60d5-359b-4f11-a8e1-3be0c4701a5c)

**Comment by saipan7** [comment]
update: although ecs486 machine don't have the freedos fdisk bug, turns out it suffer from the hdd boot fail bug:
![i1](https://github.com/86Box/86Box/assets/127716019/5ad04ab0-7340-49e2-b124-6d220f1cc3d5)
![i2](https://github.com/86Box/86Box/assets/127716019/d9599b3b-d44c-4600-8b71-7f2cea416ab0)
![i3](https://github.com/86Box/86Box/assets/127716019/6e1347f2-db76-40c2-a613-e11dca11a839)
hdd boot test:
![i51 ecs486](https://github.com/86Box/86Box/assets/127716019/69d4c1ca-c78e-4b8e-99c7-fc35b05785ed)
![i52 ecs486](https://github.com/86Box/86Box/assets/127716019/cf088394-3329-4313-a5f8-743d45481b98)

below umc machine also have similiar issue:

actionpc2600#
freedos fdisk test:
![i70 actionpc2600](https://github.com/86Box/86Box/assets/127716019/5afdee0b-24a3-443b-8406-9368576eb62a)
hdd boot test:
![i72 actionpc2600](https://github.com/86Box/86Box/assets/127716019/73909a80-a644-44c8-8278-529e159d1f57)

actiontower8400#
freedos fdisk test:
![i80 actiontower8400](https://github.com/86Box/86Box/assets/127716019/db48e29c-26bd-449f-b416-1a977f33a717)
hdd boot test:
![i82 actiontower8400](https://github.com/86Box/86Box/assets/127716019/10cb447f-1545-4af4-9a5e-bcc770654885)

hot433a#
freedos fdisk test:
![i100 hot433a](https://github.com/86Box/86Box/assets/127716019/aae0e918-1579-420c-99cb-37f2a136e734)
hdd boot test:
![i102 hot433a](https://github.com/86Box/86Box/assets/127716019/da35f0e3-8225-487f-a0d7-bf6fe72c5b8f)

spc7700plw#
freedos fdisk test:
![i90 spc7700plw](https://github.com/86Box/86Box/assets/127716019/5020b852-dac8-46fc-bb54-614fe7bf144f)
hdd boot test:
![i92 spc7700plw](https://github.com/86Box/86Box/assets/127716019/ba51bbcd-5cd2-482c-a9ff-cd29fde3137e)

although m919# have the freedos fdisk bug, but it don't suffer from the hdd boot fail bug
freedos fdisk test:
![i110 m919](https://github.com/86Box/86Box/assets/127716019/0e6de3a8-5dcf-40e8-b3a7-503b1894c3b5)
hdd boot test:
![i112 m919](https://github.com/86Box/86Box/assets/127716019/0c78d7f1-4f90-48d5-9604-f93919426588)


only 1 umc machine who don't have the freedos fdisk bug and don't suffer from the hdd boot fail bug which is the atc1415#
freedos fdisk test:
![i60 atc1415](https://github.com/86Box/86Box/assets/127716019/f334d942-3c6c-414d-bfc5-91bc2229deef)
hdd boot test:
![i62 atc1415](https://github.com/86Box/86Box/assets/127716019/3a41712f-748e-4480-9d6f-5b7ef92925c9)

**Comment by TC1995** [comment]
Could you please try the newer nightly builds? To replicate this bug I mean there too, outside 4.1.1.

**Comment by OBattler** [comment]
Go to CMOS setup and configure the hard disk correctly - your configuration shows a 37 MB drive, but it's set to 528 MB in CMOS setup.

**Comment by OBattler** [comment]
The key is to try it on a board with a different chipset but the same BIOS version - in this case, AMIBIOS 5 (101094). I tried it on the Lucky Star LS-481, which is our 101094 for SiS 496/497 and I got the exact same problem. So I conclude it's NOTABUG - the BIOS is to too old for FreeDOS, it likely requires some INT 13h extensions these BIOS'es don't support.

**Comment by OBattler** [comment]
I'm also not sure what you mean by DOS 7 - Windows 95 (which uses MS-DOS 7.00) sees the hard disks without problems.

**Comment by OBattler** [comment]
I also just tried a Windows 98 first edition boot disk, that uses MS-DOS 7.10 - FDISK also sees the hard disk without problems.

So yes, NOTABUG. FreeDOS just assumes the presence of Int 13h extensions not existent on such old BIOS'es. The MiSTer 486's BIOS likely implements said extensions.

**Comment by Thraka** [comment]
Thanks for taking a look. I know how time consuming it can be to triage issues.
