### ISSUE TITLE
Mouse and keyboard capture failure after changing floppy disk image

### ISSUE THREAD

**Issue by ghost** [86Box/86Box#481]
Problem:
After changing floppy disk image or CDROM image, the keyboard and mouse capture will stop working. The VM is still running as I can see the cursor blinking. The only way to get mouse and keyboard working again is to restart the program. 
I was using 86Box v1.XX before and I didn't experience this bug. 

Environment:
Windows 7 x64
Tried different configurations with motherboard and mouse type, problem still exists

**Comment by TC1995** [comment]
What build, configuration?

**Comment by mario1103** [comment]
> What build, configuration?

Build: v2.07, 245af88d, build2008 (zip name: 86Box-Optimized-SandyBridge-32-245af88d)
(also tried v2.06 on release page, same problem)

Configuration:
[Machine]
machine = p55tvp4
mem_size = 65536
cpu_use_dynarec = 0
time_sync = local
cpu_manufacturer = 1
cpu = 3
cpu_enable_fpu = 1

[Video]
gfxcard = px_trio64_pci
voodoo = 1

[Input devices]
mouse_type = ps2

[Other peripherals]
hdc = internal

[3DFX Voodoo Graphics]
type = 0
framebuffer_memory = 4
texture_memory = 4
bilinear = 1
dacfilter = 0
render_threads = 2
sli = 0
recompiler = 1

[Realtek RTL8019AS]
mac = b3:18:60

[Sound]
sndcard = sb16
midi_device = system_midi

[Network]
net_type = slirp
net_card = ne2kpnp

[Hard disks]
hdd_01_parameters = 63, 16, 4876, 0, ide
hdd_01_fn = D:\Program Files\86box\2400.img
hdd_01_ide_channel = 0:0

[Floppy drives]
fdd_01_type = 35_2hd
fdd_01_turbo = 1
fdd_02_type = 35_2hd
fdd_02_turbo = 1
fdd_01_fn = D:\Program Files\86box\95\Disk05.img

[Other removable devices]
cdrom_01_speed = 72
cdrom_01_parameters = 0, atapi
cdrom_01_ide_channel = 1:0
cdrom_01_host_drive = 200
cdrom_01_image_path = D:\Program Files\86box\Microsoft Windows 95C (4.03.1216) (OSR2.5) (1997-11-26) [English]\Win95_OSR25.iso

[General]
update_icons = 0


I also tried some other configurations (different motherboard, cpu, etc.), same problem. 
It seems like this bug is triggered after the windows open file dialog is shown.

**Comment by TC1995** [comment]
Have you tried the un-optimized one?

**Comment by mario1103** [comment]
> Have you tried the un-optimized one?

Just tried v2.07 unoptimized version (86Box-32-245af88d), same problem.

The bug could also be triggered by going to sound-midi-fluidsynth config- browse sound font file, 
or hard disk-existing-specify. After the windows open file dialog pops up, the keyboard and mouse capture will fail.

**Comment by TC1995** [comment]
Weird, have you tried using the jenkins dll's?

**Comment by mario1103** [comment]
> Weird, have you tried using the jenkins dll's?

You mean the latest build from Jenkins? Tried 86Box-32-ea163abd v2.10, same problem.

**Comment by OBattler** [comment]
What is your host OS?

**Comment by mario1103** [comment]
> What is your host OS?

Windows 7 x64 7601

**Comment by OBattler** [comment]
Try the latest 86Box build that removes the legacy DirectDraw and Direct3D renderers and adds the SDL Hardware renderer.

**Comment by mario1103** [comment]
> Try the latest 86Box build that removes the legacy DirectDraw and Direct3D renderers and adds the SDL Hardware renderer.

Tried 86Box-Dev-32-b6adaff6, same problem.

**Comment by OBattler** [comment]
What is your host graphics card?

**Comment by mario1103** [comment]
> What is your host graphics card? Also, do you have any IME installed on the host?

Graphics card is intel HD4000. 
IME is installed but not activated when running 86box. 
I have another computer running windows 10 with IME enabled, keyboard & mouse capture works just fine.

**Comment by OBattler** [comment]
I'm closing this because it was about the Win32 UI which is no longer being maintained.
