### ISSUE TITLE
Keyboard capture is incomplete

### ISSUE THREAD

**Issue by markfptuson** [86Box/86Box#4939]
### What happened?

Capture of keyboard input is not restricted to the guest machine; key combinations like <alt>+<tab> and <alt>+<spacebar> are picked up by the guest but are also intercepted by the host, in both fullscreen and windowed mode.

### Configuration file

```ini
<this is not a configuration issue>
```

### Operating system

Windows 11 22631.4391

### CPU

AMD 3950X

### 86Box version

4.2.1 6130

### Build architecture

Windows - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Download source

Official website (Jenkins, GitHub)

**Comment by OBattler** [comment]
This is a CANTFIX - I can't block certain key combinations from the host at all when using raw input, but I did add the "Right CTRL is left ALT" option as a workaround for that, enable that, then send ALT+TAB to the guest only by press Right CTRL+TAB.

**Comment by markfptuson** [comment]
Can you at least give an actual reason why this "_can't_" work? Because it did, and being used to it working is how I discovered that it didn't.

Maybe what you're really saying here is that I should revert my installation to 3.2.1 (3602) and stop taking updates.

**Comment by TC1995** [comment]
3.2.1 is too old.

**Comment by markfptuson** [comment]
3.2.1 _works as I need it to_, where obattler isn't even making excuses for not restoring this feature - he's just saying "no" and fobbing me off with a workaround that would need me to stop using keyboard shortcuts that I've been using for over thirty years.

**Comment by Dizzy611** [comment]
Your attitude is not endearing literally any of us to you. Go use some other software.

**Comment by markfptuson** [comment]
I'm not trying to "endear" anyone. I've spoken with obattler about this before and his response was something which I - a former programmer - saw straight through. Something about cross-compatibility, like Windows/Linux/macOS don't all support keyboard blocking.

There's any number of ways it could be done, from writing interrupts to force the OS to do nothing when certain key combinations are used (alt+space, alt+tab, &c), to having the 86box guest claim the keyboard as exclusively its own when it is the active window, with some key combination to "give it back" to the host so you can switch programs. **There are ways to do this stuff**. Hell, you could even just disable the system menu. It's really not that hard. It's not something that _can't_ be done; it's something which, for whatever reason, the 86box team _doesn't want_ to do.

**Comment by jriwanek** [comment]
We look forward to your PR. (:

**Comment by TC1995** [comment]
> 3.2.1 _works as I need it to_, where obattler isn't even making excuses for not restoring this feature - he's just saying "no" and fobbing me off with a workaround that would need me to stop using keyboard shortcuts that I've been using for over thirty years.

Except you lose the latest graphics updates ;)

**Comment by OBattler** [comment]
> 3.2.1 _works as I need it to_, where obattler isn't even making excuses for not restoring this feature - he's just saying "no" and fobbing me off with a workaround that would need me to stop using keyboard shortcuts that I've been using for over thirty years.

Blocking Alt+Tab hasn't worked in way more than that, we first stumbled on the problem during v2.00 development in 2017-18, and it was likely present before already, ever since I first changed the keyboard input code on Windows to use raw input, which was when I was still contributing back to PCem.

There's a reason i added the Right Ctrl is Left Alt workaround way before 3.2.1. And for good measure, I just tried 3.2.1 again now and no, Alt+Tab doesn't work there, at all. Now, Alt+Space is blocked yes, that was most likely broken by the switch to QT (I believe 3.2.1 still uses the Win32 UI on Windows, while already using QT on other platforms), since any keyboard hooks had been removed before then already, and if that's the case, there's even less I can do about it, since there's limits to what I can do in QT.

**Comment by OBattler** [comment]
I'm now compiling 3.2.1 with QT so I can test this and confirm or disprove my hypothesis.

**Comment by OBattler** [comment]
Hypothesis confirmed - 3.2.1 with QT has the problem already, but the version with the Win32 UI doesn't. Now, I have no idea if it's even possible to fix this with QT.

> Because it did, and being used to it working is how I discovered that it didn't.

So I have just demonstrated that Alt+Tab was never blocked (that's why I added the Right Ctrl is Left Alt workaround long before 3.2.1) and while Alt+Space was, indeed blocked, switching from the Win32 UI to QT broke it.

> I'm not trying to "endear" anyone. I've spoken with obattler about this before and his response was something which I - a former programmer - saw straight through. Something about cross-compatibility, like Windows/Linux/macOS don't all support keyboard blocking.

They do but the API is platform-specific.

> There's any number of ways it could be done, from writing interrupts to force the OS to do nothing when certain key combinations are used (alt+space, alt+tab, &c),

That would require a kernel-mode driver.

> to having the 86box guest claim the keyboard as exclusively its own when it is the active window, with some key combination to "give it back" to the host so you can switch programs.

That also can't be done with a kernel-mode driver. The reason for both this and the above should be obvious - allowing a user-mode program to do that would first be abused by malware to completely lock out the target from their OS.

> There are ways to do this stuff. Hell, you could even just disable the system menu. It's really not that hard. It's not something that can't be done; it's something which, for whatever reason, the 86box team doesn't want to do.

I'm going to look into this, if it's possible with QT, though I've had issues doing that even for the dialogs where the system menu should be disabled in accordance with the design guidelines - I tried every workaround Google found me, to no avail.

**Comment by markfptuson** [comment]
@OBattler OK, I appreciate that.

QT, that's right - now I remember you telling me. This was on Reddit, a couple of years ago. I think.

I was just blatting out ideas in my frustration before. Things like blocking the OS from acting on keyboard input are behaviours exhibited by hypervisor software - and remote desktop streaming software like Parsec. I was figuring that if those things can do it, there must be a way. Though I understand probably they don't use QT. I also understand that getting a driver signed would be a pain in the posterior and so it'd wind up getting flagged as malware itself.

For the time being at least, though, I'm going to just continue using 3.2.1. It does what I need it for, in the way I need to do it.

**Comment by OBattler** [comment]
This turns out to actually be a duplicate of this: https://github.com/86Box/86Box/issues/4399 .

**Comment by OBattler** [comment]
Which combinations exactly do I need to block, aside from ALT+TAB and ALT+SPACE?

**Comment by markfptuson** [comment]
Those are the only ones I've found are intercepted by the host OS, yes.

**Comment by OBattler** [comment]
This is now fixed.
