### ISSUE TITLE
There is problem in Hercules Monochrome Mode.

### ISSUE THREAD

**Issue by leesa49** [86Box/86Box#551]
I don't know when

In Hercules Mode,  Horizontal lines appear

![20200115-231734-255](https://user-images.githubusercontent.com/55971868/72479948-30b9dd80-3839-11ea-9465-556be04b792c.png)

![20200115-231743-075](https://user-images.githubusercontent.com/55971868/72479974-40392680-3839-11ea-8551-ae6d9974a7a4.png)

![20200115-231744-578](https://user-images.githubusercontent.com/55971868/72479976-43ccad80-3839-11ea-97a1-a82d79e09dcd.png)

![20200115-231749-637](https://user-images.githubusercontent.com/55971868/72479981-47603480-3839-11ea-8fe8-0d9e75a58564.png)

![20200115-231753-231](https://user-images.githubusercontent.com/55971868/72479989-4c24e880-3839-11ea-9c5a-bc8f70a492f7.png)

![20200115-231804-122](https://user-images.githubusercontent.com/55971868/72480002-5ba43180-3839-11ea-86d4-dbf987835e22.png)

**Comment by OBattler** [comment]
On what machine?

**Comment by Fenix770** [comment]
Hello!

I write here because I know the this game and tested the version 1.0, 1.1 and 1.3. This game has native support for the Hercules graphics card, so CGA emulation _is not required_ in for this game.

In Version 1.0 and 1.1 the game auto detects which the video card and sound device present.  (Sound Blaster, CMS game Blaster, adlib or Tandy 3-Voice with or without DAC is present)

In version 1.3 there is a setup.exe file to configure the video mode and sound options including new sound devices.

**Comment by OBattler** [comment]
So in this case, the CGA emulation driver could be interfering with the game.

**Comment by OBattler** [comment]
This is getting closed as NOTABUG, if it turns out to be in error, please post here so I can reopen it.
