### ISSUE TITLE
Check for IRQ conflicts when changing settings

### ISSUE THREAD

**Issue by daviunic** [86Box/86Box#569]
Would be nice if the emulator would check the config for IRQ conflicts whenever you select an IRQ for some device and display a warning about it.

Suggested by FreeFull on discord.

**Comment by waltje** [comment]
Real machines did not, either, that was (and should be) the fun of the experience.

     On Sunday, January 19, 2020, 9:52:46 AM EST, David Simunič <notifications@github.com> wrote:  
 
 
Would be nice of the emulator would check the config for IRQ conflicts whenever you select an IRQ for some device and display a warning about it.

**Comment by TheVirtualComputer** [comment]
I also think that people should be allowed to experiment with the machines in however way they want, and that includes simulating the experience of setting incorrect or conflicting IRQ values, especially if they wanted to study the behavior of a particular OS or software program in such cases. It's not like it's particulary hard or difficult to select the correct IRQ values either - certainly much easier than working with DIP switches or jumpers on a real adapter board.

**Comment by dhrdlicka** [comment]
At this rate, we might as well add some interface to manually interact with the DIP switches on the motherboard, because the real machines had that as well, and it was the "fun" of the experience. Why should the emulator automatically calculate the right values anyway, right?

Isn't the point of this emulator to let people easily (and properly!) run vintage software? I would say that it's exactly this kind of features like the detection of resource conflicts that create this whole "ease of use" aspect that makes emulators like 86Box more favorable compared to getting an AT-class machine ready just for a game of Planet X3 or two.

**Comment by dhrdlicka** [comment]
Furthermore, the feature request is for a **warning**. Nothing would prevent you from ignoring it and then dealing with the consequences. But why would you?

**Comment by daviunic** [comment]
Well apparently PnP and what not kinda voids this idea since IRQ settings become unpredictable, and what little is predictable just isn't worth implementing this.

**Comment by OBattler** [comment]
Yeah, MCA, ISA PnP, PCI, and eventually, EISA and AGP make prediction basically impossible as the IRQ's are not known until the BIOS (or the reference diskette) configures them, and even some normal ISA and VLB devices have overridable IRQ's (eg. Adaptec/BusLogic SCSI controllers via SCSISelect/AutoSCSI and Sound Blaster via its registers).

**Comment by OBattler** [comment]
I'm closing this as unfeasible.
