### ISSUE TITLE
Matrox does not work on Intel Premiere/PCI, Premiere/PCI II, or Classic/PCI

### ISSUE THREAD

**Issue by ghost** [86Box/86Box#605]
When trying to use either model of the Matrox Mystique with an Intel Premiere/PCI, Premiere/PCI II, or Classic/PCI system board on 86Box with the original release of Windows 95 and with the December 1997 Matrox Mystique drivers that Matrox supplied, the emulator hangs when at the hourglass screen, and the emulator window freezes.

Other Intel boards seem to be strangely unaffected by this, because I was still able to get it to work with the newer Advanced/ATX board, and I also know for a fact that SarahWalker of PCem was testing it with either an Intel Advanced/EV or Advanced/ZP, but it still doesn't seem to work on the three older system boards.

**Comment by nerd73** [comment]
Known issue, also affects anything post-430FX.

**Comment by TheVirtualComputer** [comment]
Currently, I'm trying it with an Intel Advanced/ZP, with all ISA devices removed except for the Creative Labs Sound Blaster AWE32. I'm performing a clean install of Windows 95. Previously, I was able to get it to work temporarily, but then the system redetected all PCI devices and reconfigured the display adapter to use a memory region that conflicted with the network driver, so I'm completely reinstalling the operating system just to make sure that all new hardware settings are used.

If this issue affects all newer boards however than that makes this issue even more concerning since there were many models of PCs with newer boards and chipsets that used the Matrox adapters and the Matrox Millennium and Mystique in particular, which would mean that something is seriously wrong with the Matrox emulation code if that happens to be the case.

Has anyone tried investigating this issue?

**Comment by OBattler** [comment]
It works on 430FX machines, and no others, also happens on PCem. On all other chipsets it uses DMA and unimplemented commands. I can't do much about this, so I'm doing to Dev branch it for time being.

**Comment by OBattler** [comment]
Closing this since the reporter's GitHub account has disappeared.

**Comment by OBattler** [comment]
Recategorizing this issue as this is now actually fixed.
