### ISSUE TITLE
ATI Mach64 does not work correctly in latest revisions

### ISSUE THREAD

**Issue by ghost** [86Box/86Box#777]
It is quite obvious that the developers did not fully test their video code before submitting it, because In the latest revisions, the ATI Mach64 is nearly useless. When using a PCI board, for example, the hardware cursor does not appear, and some Mach64 drivers are non-functional, while the ISA version is almost completely useless and does not even display the graphics correctly.

This occurs on the latest revision of 86Box. Specifically, I was using the Acer M3a board and an ATI Mach64 GX adapter (the VT2 and later were already available by the time that the M3a was being made, but I was setting it up to emulate the hardware configuration of an earlier Acer model).

I have tested this with the original release of Windows 95 with the Microsoft DirectX drivers, as well as a pre-release version of Windows 95 OSR2 (1.00.1009b) with another set of DirectX drivers, and with the official ATI Mach64 drivers that were provided by ATI. Earlier versions of 86Box did not exhibit this behavior at all, so it was definitely introduced in the WIP revisions from February and later.

**Comment by qeeg** [comment]
Says the guy who makes a massive machine list for his 86Box fork, and tests approximately none of his new additions.

**Comment by dhrdlicka** [comment]
> It is quite obvious that the developers did not fully test their video code before submitting it, because In the latest revisions, the ATI Mach64 is nearly useless.

Please drop this accusative tone, after all we are only humans and it's not in our powers to test every single configuration. Furthermore, you replaced the standard bug report template. It's there for a reason.

Could you please bisect to see what build broke the Mach64?

**Comment by TheVirtualComputer** [comment]
I am already working on a fix for some of these issues - I have already corrected the problems with the mouse pointer by reverting many of the changes that were made in February, and I am also investigating the issues with the ISA-based ATI Mach64 boards, and once I'm finished then I will provide the files with the fixes.

**Comment by dhrdlicka** [comment]
The issue should stay open until it gets fixed.

**Comment by TheVirtualComputer** [comment]
Well, it looks like I was finally able to correct both of the problems, first by reverting all of the code changes and then by changing the old code to work with the newly updated source tree and include files.

The first issue was resolved by reverting to the old code that was previously used for the hardware pointer support, which was achieved by reverting the changes made in February, then by updating the old code to work with the source tree and by updating the vid_svga.h file to have the duplicate Mach64 definitions disabled.

The second issue was resolved (although in a less-than-ideal way) by reverting the more recent changes that were apparently intended to separate the VESA/VL-Bus timings from the PCI timings - apparently this more recent change (from what I can tell) was done in a way that somehow disabled some of the memory-mapping code that was required for the ISA-based Mach64 boards, which explains why the graphics were not being drawn correctly. I am not entirely satisfied with this fix since it basically means that the PCI-based Mach64 boards are now (once again) using the VL-Bus timings, but at least all of the Mach64 boards are working again.

The corrected files can be found here:
[video.zip](https://github.com/86Box/86Box/files/4701215/video.zip)

**Comment by dhrdlicka** [comment]
Could you please submit your fixes as a Pull Request?

**Comment by nerd73** [comment]
@TheVirtualComputer These are not proper fixes for the problems mentioned above.

**Comment by TheVirtualComputer** [comment]
The problem here is that my code was not from an actual repository but rather from my private PC, which is why I had to provide the files here instead. To do a pull request would mean having to create an entire new repository/source tree and then "fork" it from there, which would take up a lot more time.

nerd73: This was the only way that I could find in order to get the Mach64 boards working again. The first issue was already serious enough to be a major problem, and the second issue rendered the ISA-based boards practically useless. It's either this or the issues simply don't get fixed until someone else finds a better fix for this than I did.

**Comment by qeeg** [comment]
Why wouldn't you just fork the repository in the first place? It's really not that hard.

**Comment by qeeg** [comment]
Also, stop acting like you're so much better at this than us, all your dumb fork does is add fucktons of machines that don't work well AT ALL, and instead you just forward all bug reports to us. Get off your fucking high horse, and start TRYING for once.

**Comment by TheVirtualComputer** [comment]
You know what, qeeg? If you continue to insult me like that and tell me that you hate everything that I stand for then I'll no longer post here at all. Nowhere did I do anything to you to even warrant such a response. Absolutely nowhere did I in ANY way say anything that was even remotely angrily directed at you in particular until now. If you seriously hate me that much that you would go on attacking me like that like that, then I'm taking my entire source repository offline so that no one can access it anymore, and I won't post anymore new emulator releases at all until people at least show some respect for other people's work.

1. I never said anything that was at all angry or hostile towards you, so why did you do the same to me and act as if I did?
2. This issue was not about my own private projects which have a very difference audience then 86Box does, which are still in pre-release stage at that (which is why you were still finding problems since those features were marked as being incomplete/unfinished), and which I never intended to be discussing here at all (the only reason why I even mentioned it at all was that you brought it up).
3. If you said that in real life then you can be sure as ever that any reasonable person would simply not want to be your friend anymore. It's called bullying. If you would seriously hate someone so much as to keep harassing them then and using foul language like that then I have to wonder why projects like these even have a bug reporting section at all if people are just going to get attacked for it like they were trying to burn someone's house down.

So I'm basically done with the emulator scene as it is, and so with that I'm going to close my account and take down my entire repository along with it, and continue all of my emulator development in private where absolutely no one can harass me for it.
