### ISSUE TITLE
How to install Windows 98 on 86Box 2.10

### ISSUE THREAD

**Issue by HomerBender77** [86Box/86Box#781]
Hello. I've been trying to figure out how to install Windows 98 on 86Box 2.10. I made an HDD image and inserted an ISO of Windows 98, but nothing really happens. I've looked at all the guides but they're for 86Box 2.00 which has a slightly different interface. Any advice?

**Comment by daviunic** [comment]
Hi, please provide all the relevant information - config, source of the ISO image you used, number and type of 86Box build you're using, whether you configured the BIOS accordingly, etc.

**Comment by HomerBender77** [comment]
I've got 86Box 2.10, build 2306. I have a Windows 98 SE Arabic ISO which i dowloaded from Google Drive. But I don't know how to configure the BIOS. Does config refer to the 86box.cfg file?

**Comment by daviunic** [comment]
> Does config refer to the 86box.cfg file?

Yes.

> But I don't know how to configure the BIOS. 

This depends on the machine you're using. As said, providing the complete config would be the best option.

**Comment by HomerBender77** [comment]
[86box.zip](https://github.com/86Box/86Box/files/4732101/86box.zip)
Here is the CFG file.

**Comment by OBattler** [comment]
1. Make sure that the floppy drives in CMOS setup are configured exactly like in 86Box settings and that any IDE hard disks and CD-ROM drivers are detected there;
2. You need a Windows 98 SE boot disk with a CD-ROM driver so you can boot and begin installing Windows, try looking on allbootdisks.com - the boot disk can be English even if the OS is Arabic;
3. Boot from the boot disk.

**Comment by HomerBender77** [comment]
Thanks. How can I configure the floppy drives in CMOS setup? I looked but couldn't find out.

**Comment by igdegoo** [comment]
hold delete on startup usually

**Comment by HomerBender77** [comment]
Unfortunately, I tried to do that but it didn’t work. When I press esc to go to the startup menu, the options offered are:

F1 - System Information
F2 - System Diagnostics
F9 - Boot device options
F10 - BIOS Setup

Enter - Continue Startup

**Comment by qeeg** [comment]
BIOS Setup is what you want.

**Comment by HomerBender77** [comment]
I am now there. But I don’t see options to configure floppy drives just like in 86Box settings.

**Comment by qeeg** [comment]
Dude... just think for yourself here. Look through the menus, it's not that hard.

**Comment by dhrdlicka** [comment]
You are supposed to enter the BIOS setup of the VM, not your host computer. According to your `86box.cfg`, that should be an AMI BIOS.

![image](https://user-images.githubusercontent.com/13226155/83954033-d0f2bc00-a845-11ea-95b0-49d69b5ba918.png)

When you see the above screen, press `Del`. You will probably want to spam the key straight from start, as the BIOS doesn't wait for long. That should land you at the following screen:

![image](https://user-images.githubusercontent.com/13226155/83954064-19aa7500-a846-11ea-9bb3-2469a508f51d.png)

If you configured mouse properly, you should be able to capture the mouse by clicking the VM screen, then you can use the mouse to click buttons in the GUI. Otherwise, just use arrow keys, `Tab`, `Enter`, and `Esc` to navigate the interface. Floppy configuration is under the _Standard_ icon:

![image](https://user-images.githubusercontent.com/13226155/83954083-4f4f5e00-a846-11ea-9c74-78750153da32.png)

There, choose a floppy drive icon to configure its type. `A:` corresponds to the first floppy drive in 86Box settings, `B:` is the second one. Here I have set the first floppy drive to 3.5" 1.44 MB in 86Box settings and configured the floppy drive A: to correspond.

![image](https://user-images.githubusercontent.com/13226155/83954148-cdac0000-a846-11ea-8961-dc6ec4e922dc.png)

All that's left to do is save the settings. Press `Esc` until you see the following screen and then press `Enter`. Alternatively, click the minus sign button in the top left corner and then click the first button.

![image](https://user-images.githubusercontent.com/13226155/83954162-0b108d80-a847-11ea-8b2e-e416a006c9d8.png)

**Comment by HomerBender77** [comment]
Thank you very much. I have done it now. Now I just need to get 86Box to recognize my HDD image.

**Comment by OBattler** [comment]
Again in CMOS Setup, go to Detect IDE and let it detect all IDE devices. Then save the configuration and reboot.

**Comment by HomerBender77** [comment]
I did that now too. And I just got the 98 OS installed onto the HDD image. But I now have two new problems:
*Emulation is very slow at around 15%.
*I ended up using a different machine to install the OS, specifically Gigabyte GA-686NX. The OS boots up fine under that machine, but when I switch back to the Super Micro machine, I get an "I/O Error" or something like like.

**Comment by daviunic** [comment]
> Emulation is very slow at around 15%.

You're probably emulating a too fast CPU that your host can't emulate at decent accuracy. Try downgrading to a slower model, generally you want to stay above 90% consistently for a decent experience. Keep in mind that some things like using a higher screen resolution with more colors can negatively affect performance.

> I ended up using a different machine to install the OS, specifically Gigabyte GA-686NX. The OS 
boots up fine under that machine, but when I switch back to the Super Micro machine, I get an "I/O Error" or something like that. 

Windows probably picked up drivers for the new board when you first booted on it, then when you switched back something broke. It's often better to just reinstall these later versions of Windows when changing boards to avoid complications like these.

> Another question: How can I easily exit full-screen mode?

Control + Alt + Page down.

**Comment by HomerBender77** [comment]
I've changed the CPU to a Pentium Pro 50 (it was previously a Pentium Overdrive 333 or something) and it's now faster, but now around 60-70%.

**Comment by kkwpsv** [comment]
Maybe you need a better host cpu...

**Comment by HomerBender77** [comment]
Okay. But when I try to install Windows ME on another HDD image, even after all the formatting, setup doesn't run.

**Comment by kkwpsv** [comment]
> Okay. But when I try to install Windows ME on another HDD image, even after all the formatting, setup doesn't run. The host CPU is an AMD A10-9600P Raedon R5.

Windows ME need a more than 150 Mhz CPU to install. After installation, you can switch to a another CPU.
Your host cpu is too poor to simulate a 150 Mhz CPU.....

**Comment by HomerBender77** [comment]
I switched to a 150 Mhz CPU and steup still doesn't run.

**Comment by dhrdlicka** [comment]
What do you mean by "setup doesn't run"? Could you post a screenshot?

**Comment by HomerBender77** [comment]
I meant that when I type setup at the command prompt it just does nothing and goes back to the command line. But I found the problem now, and it's with the ISO which I was using.
