### ISSUE TITLE
Asterix Operation Getafix (1989) not playable

### ISSUE THREAD

**Issue by Fenix770** [86Box/86Box#927]
**Describe the bug**
 
According  "Total Dos Collection release 17" (TDC). This particular game has a special routine to check the CPU speed. I suspect it's some kind of routine not emulated and for this reason is too slow to be playable either on 8088 or a 386 DX/25. I had the original Spanish version back in the day and worked correctly on a XT machine with the Hercules graphics card.

Also, I have a Spanish version patched by Italsoft, that works right on 286 at 10 mhz and lesser. But it is too fast on 386 DX/25.

**To Reproduce**

On the orinigal non patched version:
1. run LOADER.EXE from A:\ prompt 
(1b. For the italsoft: press space to the ad screen)
2. Select video mode Hercules/CGA/VGA. (This game also supports the Covox Speech Thing for soud effect)
3. Select 'No' when ask to load a previous saved game.

**Expected behavior**
The non-patched version should work right on XT machines.

Image files: 
[Asterix Operation Getafix original.zip](https://github.com/86Box/86Box/files/4922456/Asterix.Operation.Getafix.original.zip)
[Asterix operation getafix spanish cracked.zip](https://github.com/86Box/86Box/files/4922458/Asterix.operation.getafix.spanish.cracked.zip)

**Desktop (please complete the following information):**
 - OS:  Windows 10 ver 1909
 - 86Box version: Latest commit
 - Build type: regular

**Additional context**
Can, this bug, be related to other bugs with some CGA emulator programs for some games? 
Or these emulators expect to find some obscure/ non documented functions not documented of the Hercules card? (For example Arkanoid 1 throws an error saying CGA or better is required even when CGA emulation is installed)

**Comment by OBattler** [comment]
The thing is, the emulation of pretty much every graphics cards needs to be rewritten so that timers run per character clock rather than per line, until that's done, hsync status will always be bogus and therefore any routine that relies on it (which I assume most if not all of these do), will behave in unpredictable ways.

**Comment by OBattler** [comment]
> and worked correctly on a XT machine with the Hercules graphics card.
But did that XT machine have an 8088 4.77 MHz?

**Comment by eddmanx** [comment]
The original game you've posted seems to be bad. After step 3, pressing "No", the game runs in super slow motion and takes ages for the text box to go away, and then it basically gets stuck.

I tried another image and it works fine. I have no sound but that's probably because I haven't set up the audio correctly.

[Astérix- Operation Getafix (1989)(Coktel Vision) [IMA][720k].zip](https://github.com/user-attachments/files/16430242/Asterix-.Operation.Getafix.1989.Coktel.Vision.IMA.720k.zip)

**Comment by OBattler** [comment]
Then this can be closed as NOTABUG.
