### ISSUE TITLE
[TYPO] "New Floppy Image" menu title displayed on creation of ZIP and MO devices

### ISSUE THREAD

**Issue by ppgrainbow** [86Box/86Box#935]
I would like to report a typo in the menu title name when creating Iomega ZIP or magneto-optical images.

First, when I create a new Iomega ZIP disk image by selecting "New image" when clicking on the Iomega ZIP disk icon or selecting ZIP 100/250 in the Media menu dialog, I get this:
![ZIP](https://user-images.githubusercontent.com/32658796/87868100-c436ad00-c947-11ea-8df2-212d5d318023.png)

And lastly when I create a new magneto-optical disk image by selecting "New image" when clicking on the magneto-optical disk icon or selecting a MO disk in the Media menu dialog, I get this:
![MO](https://user-images.githubusercontent.com/32658796/87868102-c7319d80-c947-11ea-9e60-b1b227101f22.png)

To fix this problem, the menu title should the following:

For ZIP drives, it should say, "New ZIP Image" and for magneto-optical drives, it should say, "New MO Image".

I hope that this helps. :)

**Comment by maximus105** [comment]
Since in the settings windows all names begin with a capital letter, an error is present in the form: FD Controller (Internal controller). In the word "controller", the first letter must be capitalized.

![Floppy](https://user-images.githubusercontent.com/58270614/87875226-7f0e8b80-c9d8-11ea-95e0-780623cca243.jpg)
